#!/bin/sh
#
# Script for use within user's jobscript to get the DIDs of all files 
# allocated to this job
#
# Jobscripts can execute this script as: $JUSTIN_PATH/justin-allocated-files
#
# Error messages to stderr
# Zero or more DIDs to stdout, one per line
#

if [ ! -r "$JUSTIN_PATH/justin-allocated-files.json" ] ; then
  echo "$JUSTIN_PATH/justin-allocated-files.json not found!" >&2
  exit 2
fi

ALLOCATED_FILES_TMP=`mktemp /tmp/justin_allocated_files_XXXXXX`

http_code=`curl \
--user-agent 'justin-allocated-files' \
--silent \
--header "X-Jobid: $JOBSUBJOBID" \
--header "Accept: text/plain" \
--capath ${X509_CERTIFICATES:-/etc/grid-security/certificates/} \
--data @$JUSTIN_PATH/justin-allocated-files.json \
--output $ALLOCATED_FILES_TMP \
--write-out "%{http_code}\n" \
https://justin-allocator-pro.dune.hep.ac.uk/api/allocator/get_allocated_files 2>/dev/null`

if [ "$http_code" = 200 ] ; then
 cat $ALLOCATED_FILES_TMP
 retcode=0
else
 echo "justin-allocated-files receives:" >&2
 cat $ALLOCATED_FILES_TMP >&2
 echo >&2
 echo "justin-allocated-files fails with HTTP code $http_code!" >&2
 retcode=1
fi

rm -f $ALLOCATED_FILES_TMP
exit $retcode
