#!/usr/bin/env python3
#
# scratch-fnal-upload - upload file to dCache scratch at Fermilab
#
# Copyright 2013-23, Andrew McNab for the University of Manchester
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

import os
import os.path
import sys
import json
import time
import ssl
import urllib.request

# curl -v -v -L --cert /tmp/justin-jobs-analysis.proxy.pem --capath /etc/grid-security/certificates --request MKCOL  'https://fndcadoor.fnal.gov:2880/dune/scratch/justin/amcnab@fnal.gov'
# curl -v -v -L --cert /tmp/justin-jobs-analysis.proxy.pem --capath /etc/grid-security/certificates --upload /tmp/123.txt https://fndcadoor.fnal.gov:2880/dune/scratch/justin/amcnab@fnal.gov/1/2/444.txt

# curl -v -v -L --header "Authorization: Bearer $AT" --capath /etc/grid-security/certificates --upload /tmp/123.txt https://fndcadoor.fnal.gov:2880/dune/scratch/users/amcnab/501.txt
