#
# Copyright 2013-24, Andrew McNab for the University of Manchester
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# This list of sequences is just used to define the types of events
# We use exec() in __init__.py to create variables for each event which will
# fail at runtime if you get the names wrong in the code
#
# IF THIS LIST IS MODIFIED YOU MUST RERUN docs/event-types-to-markdown TO
# UPDATE THE LIST OF EVENTS IN THE DOCS TOO! 
# 
eventsList = [

# Workflow / stage events in dashboard or command
('WORKFLOW_CREATED',
 101,
 'Workflow created'),
('STAGE_CREATED',
 102,
 'Stage created'),
('WORKFLOW_SUBMITTED',
 103,
 'Workflow has been submitted'),
('WORKFLOW_PAUSED',
 104,
 'Workflow has been paused'),
('WORKFLOW_RESTARTED',
 105,
 'Workflow has been restarted'),
('WORKFLOW_FINISHED_BY_USER',
 105,
 'Workflow marked finished by user '),
('WORKFLOW_PAUSED_NOTUSED',
 106,
 'Workflow paused, too many Notused jobs'),
('WORKFLOW_PAUSED_NONE_PROCESSED',
 107,
 'Workflow paused, too many None Processed jobs'),
('WORKFLOW_PAUSED_JOBSCRIPT_ERROR',
 108,
 'Workflow paused, too many jobscript errors'),
('WORKFLOW_STOPPED_TOO_MANY_FILES',
 109,
 'Workflow stopped, too many input files'),

# Workflow/stage/file/replica set-up/finish events in Finder
('FILE_ADDED',
 201,
 'File added to first stage by Finder'), 
('REPLICA_ADDED',
 202,
 'Replica added for file by Finder'),
('REPLICA_STAGING_REQUESTED',
 203,
 'Finder requests replica staging'),
('REPLICA_STAGING_DONE',
 204,
 'Replica staging requested by Finder is done'),
('REPLICA_STAGING_CANCELLED ', 
 205,
 'Replica staging cancelled by Finder'),
('WORKFLOW_STARTED_BY_FINDER',
 206,
 'Finder starts the workflow running'),
('WORKFLOW_FINISHED_BY_FINDER',
 207,
 'Workflow marked finished by Finder'),

# Job-level events
('JOB_SUBMITTED', 
 301,
 'Job submitted by factory'),
('JOB_STARTED', 
 302,
 'Job started running at site'),
('JOB_PROCESSING', 
 303,
 'Job began processing files'),
('JOB_OUTPUTTING', 
 304,
 'Job began outputting files to storage'),
('JOB_FINISHED', 
 305,
 'Job finished'),
('JOB_NOTUSED', 
 306,
 'Job was not allocated a stage'),
('JOB_ABORTED', 
 307,
 'Job aborted'),
('JOB_STALLED_HEARTBEAT', 
 308,
 'Job stalls with missing heartbeats'),
('JOB_SCRIPT_ERROR', 
 309,
 'Error raised by the jobscript'),
('JOB_OUTPUTTING_FAILED', 
 310,
 'Job outputting failed'),
('JOB_STALLED_HTCONDOR', 
 311,
 'Job stalls as absent from HTCondor'),
('JOB_ABORT_RECORDING_RESULT',
 312,
 'Job aborted when recording results'),
('JOB_ABORT_CREATING_LOGS_TGZ',
 313,
 'Job aborted when creating logs.tgz'),
('JOB_ABORT_METACAT_LOGS_CREATION',
 314,
 'Job aborted when creating logs.tgz JSON'),
('JOB_ABORT_METACAT_LOGS_REGISTRATION',
 315,
 'Job aborted when registering logs.tgz'),
('JOB_ABORT_RUCIO_UPLOAD_LOGS',
 316,
 'Job aborted when uploading logs.tgz'),
('JOB_ABORT_WEBDAV_UPLOAD',
 317,
 'Job aborted during WebDAV upload'),
('JOB_ABORT_CREATING_METADATA',
 318,
 'Job aborted creating metadata json'),
('JOB_ABORT_METACAT_REGISTRATION',
 319,
 'Job aborted during file MetaCat registration'),
('JOB_ABORT_RUCIO_UPLOAD_FILE',
 320,
 'Job aborted during file Rucio upload'),
('JOB_ABORT_METACAT_UPLOADED',
 321,
 'Job aborted during MetaCat set uploaded'),
('JOB_ABORT_METACAT_CONFIRMED',
 322,
 'Job aborted during MetaCat set confirmed'),
('JOB_ABORT_CVMFS_CHECKS',
 323,
 'Job aborted during cvmfs checks'),
('JOB_ABORT_SCRIPT_ERROR',
 324,
 'Job aborted due to jobscript error'),
('JOB_NONE_PROCESSED', 
 325,
 'Job asked for no files or processed none of those allocated'),

# File-level events during running
('FILE_ALLOCATED', 
 401,
 'File allocated to job'),
('FILE_ALLOCATED_RESET', 
 402,
 'File set back to unallocated from allocated'),
('FILE_SET_TO_FAILED', 
 403,
 'Too many attempts to process file: failed'),
('FILE_CREATED', 
 404,
 'Output file created in job'),
('FILE_OUTPUTTING_RESET', 
 405,
 'File set back to unallocated from outputting'),
('FILE_UPLOADED', 
 406,
 'Output file uploaded in job'),
('FILE_PROCESSED', 
 407,
 'Input file processed by jobscript'),

# AWT events 
('AWT_READ_OK', 
 501,
 'AWT read test succeeds'),
('AWT_READ_FAIL', 
 502,
 'AWT read test fails'),
('AWT_WRITE_OK', 
 503,
 'AWT write test succeeds'),
('AWT_WRITE_FAIL', 
 504,
 'AWT write test fails'),

# Site and storage events
('SITE_ENABLED', 
 601,
 'Site is marked as enabled for jobs'),
('SITE_DISABLED', 
 602,
 'Site is marked as disabled for jobs'),
('STORAGE_READ_ENABLED', 
 603,
 'RSE is marked as enabled for reading'),
('STORAGE_READ_DISABLED', 
 604,
 'RSE is marked as disabled for reading'),
('STORAGE_WRITE_ENABLED', 
 605,
 'RSE is marked as enabled for writing'),
('STORAGE_WRITE_DISABLED', 
 606,
 'RSE is marked as disabled for writing')

]
