#!/bin/sh
# Clone justIN from GitHub, run build-justin-container, and restart services/agents
#
# Run from anywhere like this:
#
# clone-build-justin-container
# clone-build-justin-container TAG
# clone-build-justin-container BRANCH
#
# You could put it in /root/bin 
#
#
# Copyright 2013-26
# Andrew McNab for the University of Manchester
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

cd /tmp
rm -f /var/run/justin/overrides/*
rm -Rf /tmp/dune-justin/
git clone https://github.com/DUNE/dune-justin.git

if [ "$1" != "" ] ; then
  git checkout "$1"
fi

cd dune-justin
containers/build-justin-container --restart
