#!/bin/bash
# Install in /usr/sbin

if [ "$1" == "justin-httpd" ] ; then
  extras='--volume /etc/justin-letsencrypt:/etc/justin-letsencrypt --volume /var/log/httpd:/var/log/httpd --publish 80:80 --publish 443:443'
fi

tag=`/usr/bin/docker images --format 'table {{.Tag}}' | head -2 | tail -1`

exec /usr/bin/docker run --rm --name $1 --privileged \
  --env=CONTAINER_NAME=$1 \
  --volume /etc/justin.d:/etc/justin.d \
  --volume /etc/justin-secrets:/etc/justin-secrets \
  --volume /var/log/justin:/var/log/justin \
  --volume /var/run/justin:/var/run/justin \
  $extras justin:$tag \
  /usr/sbin/start-$1
