#!/bin/bash
# Install in /usr/sbin if run from systemd
# 

if [ "$1" == "justin-httpd" ] ; then
  extras="--volume $JUSTIN_VOLUMES/etc/justin-letsencrypt:/etc/justin-letsencrypt --volume $JUSTIN_VOLUMES/var/log/httpd:/var/log/httpd --publish 80:80 --publish 443:443"
fi

tag=`podman images --format 'table {{.Tag}}' | head -2 | tail -1`

exec podman run --rm --name $1 \
  --env=CONTAINER_NAME=$1 \
  --volume $JUSTIN_VOLUMES/etc/justin.d:/etc/justin.d \
  --volume $JUSTIN_VOLUMES/etc/justin-secrets:/etc/justin-secrets \
  --volume $JUSTIN_VOLUMES/var/log/justin:/var/log/justin \
  --volume $JUSTIN_VOLUMES/var/run/justin:/var/run/justin \
  $extras justin:$tag \
  /usr/sbin/start-$1
