#!/bin/bash
# Install in /usr/sbin if run from systemd
# 

if [ "$1" == "justin-httpd" ] ; then
  extras="--volume $JUSTIN_VOLUMES/etc/justin-letsencrypt:/etc/justin-letsencrypt --volume $JUSTIN_VOLUMES/var/log/httpd:/var/log/httpd"
fi

if [ "$1" == "justin-mariadb" ] ; then
  extras="--volume $JUSTIN_VOLUMES/var/lib/mysql:/var/lib/mysql"
fi

# Create justin-pod if not already existing
podman pod exists justin-pod
if [ $? != 0 ] ; then
  podman pod create --publish 3306:3306 --publish 80:80 --publish 443:443 \
                    justin-pod
fi

tag=`podman images --format 'table {{.Tag}} {{.Repository}}' | grep 'localhost/justin' | cut -f1 -d' ' | head -1`

podman run --rm --name $1 --pod justin-pod \
  --env=CONTAINER_NAME=$1 \
  --volume $JUSTIN_VOLUMES/etc/justin.d:/etc/justin.d \
  --volume $JUSTIN_VOLUMES/etc/justin-secrets:/etc/justin-secrets \
  --volume $JUSTIN_VOLUMES/var/log/justin:/var/log/justin \
  --volume $JUSTIN_VOLUMES/var/run/justin:/var/run/justin \
  $extras justin:$tag \
  /usr/sbin/start-$1 
 