#!/bin/sh
# Start httpd, for execution inside the justin container
#
# Copyright 2013-24 Andrew McNab for the University of Manchester
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# All processes get this defined
echo "CONTAINER_NAME=$CONTAINER_NAME" >>/etc/environment

# Create a set of VOMS proxies
/etc/cron.daily/justin-create-x509-proxies

# Start crond (just to refresh VOMS proxies?)
/usr/sbin/crond

# Set up and start munge daemon, which runs in the background
cp -f /etc/justin-secrets/munge.key /etc/justin-secrets/munge.key.b64 \
      /etc/munge
chown munge.munge /etc/munge/munge.key*
chmod 0400 /etc/munge/munge.key*

# su requires that munge has an executable shell not nologin 
chsh -s /bin/bash munge
su -c /usr/sbin/munged munge
if [ $? != 0 ] ; then
  echo "Failed to start munged - exiting ($?)"
  exit 1
fi

# Update docs from GitHub
/var/lib/justin/justin-update-docs

pro_dev=`grep -h '^pro_dev' /etc/justin.d/*.conf|sed 's/^.*= *\([a-z]*\)/\1/'`
if [ "$pro_dev" = "" ] ; then
  pro_dev=pro
fi

ln -sf /etc/justin-secrets/justin-allocator-$pro_dev.dune.hep.ac.uk.cert.pem \
       /etc/grid-security/justin-allocator.cert.pem
ln -sf /etc/justin-secrets/justin-allocator-$pro_dev.dune.hep.ac.uk.key.pem \
       /etc/grid-security/justin-allocator.key.pem

ln -sf /etc/justin-secrets/justin-ui-$pro_dev.dune.hep.ac.uk.cert.pem \
       /etc/grid-security/justin-ui.cert.pem
ln -sf /etc/justin-secrets/justin-ui-$pro_dev.dune.hep.ac.uk.key.pem \
       /etc/grid-security/justin-ui.key.pem

ln -sf \
 /etc/justin-letsencrypt/live/justin-$pro_dev.dune.hep.ac.uk/fullchain.pem \
 /etc/grid-security/justin.cert.pem
ln -sf \
 /etc/justin-letsencrypt/live/justin-$pro_dev.dune.hep.ac.uk/privkey.pem \
 /etc/grid-security/justin.key.pem
ln -sf /etc/justin-letsencrypt/* /etc/letsencrypt/            

echo "#!/bin/sh" > /etc/cron.daily/run-certbot
echo "certbot --config-dir /etc/justin-letsencrypt renew >/var/log/run-certbot.log 2>&1" \
 >> /etc/cron.daily/run-certbot
chmod +x /etc/cron.daily/run-certbot

if [ -x /var/run/justin/overrides/justin-wsgi-dashboard ] ; then
  cp -f /var/run/justin/overrides/justin-wsgi-dashboard /var/www/wsgi/
fi

if [ -x /var/run/justin/overrides/justin-wsgi-allocator ] ; then
  cp -f /var/run/justin/overrides/justin-wsgi-allocator /var/www/wsgi/
fi

if [ -x /var/run/justin/overrides/justin-wsgi-ui ] ; then
  cp -f /var/run/justin/overrides/justin-wsgi-ui /var/www/wsgi/
fi

# Run daemon in the foreground
/usr/sbin/httpd -DFOREGROUND
