#!/bin/sh
# Start justin-fnal-agent, for execution inside the justin container
#
# Copyright 2013-24 Andrew McNab for the University of Manchester
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# All processes get this defined
echo "CONTAINER_NAME=$CONTAINER_NAME" >>/etc/environment

# Create a set of VOMS proxies
/etc/cron.daily/justin-create-x509-proxies

# Start crond (just to refresh VOMS proxies?)
/usr/sbin/crond


# Run daemon in the foreground
if [ -x /var/run/justin/overrides/justin-fnal-agent ] ; then
  /var/run/justin/overrides/justin-fnal-agent
else
  /usr/sbin/justin-fnal-agent
fi
