#!/bin/sh
# Start justin-info-collector, for execution inside the justin container
#
# Copyright 2013-24 Andrew McNab for the University of Manchester
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Set up and start munge daemon, which runs in the background
cp -f /etc/grid-security/munge.key /etc/grid-security/munge.key.b64 \
      /etc/munge
chown munge.munge /etc/munge/munge.key*
chmod 0400 /etc/munge/munge.key*

# su requires that munge has an executable shell not nologin 
chsh -s /bin/bash munge
su -c /usr/sbin/munged munge
if [ $? != 0 ] ; then
  echo "Failed to start munged - exiting ($?)"
  exit 1
fi

# Run daemon in the foreground
/usr/sbin/justin-info-collector --container
