#!/bin/sh
# Start justin-job-factory, for execution inside the justin container
#
# Copyright 2013-24 Andrew McNab for the University of Manchester
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# All processes get this defined
echo "CONTAINER_NAME=$CONTAINER_NAME" >>/etc/environment

# Create a set of VOMS proxies
/etc/cron.daily/justin-create-x509-proxies

# Start crond (just to refresh VOMS proxies?)
/usr/sbin/crond

# Set up and start munge daemon, which runs in the background
cp -f /etc/justin-secrets/munge.key /etc/justin-secrets/munge.key.b64 \
      /etc/munge
chown munge.munge /etc/munge/munge.key*
chmod 0400 /etc/munge/munge.key*

# su requires that munge has an executable shell not nologin 
chsh -s /bin/bash munge
su -c /usr/sbin/munged munge
if [ $? != 0 ] ; then
  echo "Failed to start munged - exiting ($?)"
  exit 1
fi

if [ -f /var/run/justin/overrides/dev.conf ] ; then
  cp -f /var/run/justin/overrides/dev.conf /etc/justin.d/
fi
cp -f /etc/justin-secrets/secrets.conf /etc/justin.d/
 
# Run daemon in the foreground
if [ -x /var/run/justin/overrides/justin-job-factory ] ; then
  /var/run/justin/overrides/justin-job-factory --container
else
  /usr/sbin/justin-job-factory --container
fi
