#!/bin/sh
#
# sudo wrapper for condor_transfer_data
#
# Place this in /etc/sudoers.d/justin-get-output-sudoer
# apache ALL=(mcnab) NOPASSWD: /var/lib/justin/justin-get-output
# 

JOB=`echo "$1" | sed 's/[^0-9.]//g'`

condor_transfer_data "$JOB" >/dev/null 2>&1

echo "======="
echo "======= Start of job $JOB log"
echo "======="
if [ -r "/tmp/justin-wrapper-$JOB.log" ] ; then
 cat "/tmp/justin-wrapper-$JOB.log"
else
 echo '(missing - deleted?)'
fi
echo
echo "======="
echo "======= Start of job $JOB output"
echo "======="
if [ -r "/tmp/justin-wrapper-$JOB.out" ] ; then
 cat "/tmp/justin-wrapper-$JOB.out"
else
 echo '(missing - deleted?)'
fi
