#!/bin/sh
#
# Wrapper for condor_transfer_data etc
# 

cluster="$1"
proc="$2"
schedd="$3"

condor_transfer_data -name "$schedd" "$cluster.$proc" >/dev/null 2>&1

echo "======="
echo "======= Start of condor_q -better -name $schedd $cluster.$proc output"
echo "======="
/usr/bin/condor_q -better -name "$schedd" "$cluster.$proc"
echo "======="
echo "======= Start of job $cluster.$proc@$schedd log"
echo "======="
if [ -r "/tmp/justin-wrapper-$cluster.$proc.$schedd.log" ] ; then
 cat "/tmp/justin-wrapper-$cluster.$proc.$schedd.log"
else
 echo '(missing - deleted?)'
fi
echo "======="
echo "======= Start of condor_q -name $schedd -long $cluster.$proc"
echo "======="
/usr/bin/condor_q -name "$schedd" -long "$cluster.$proc"
echo
echo "======="
echo "======= Start of job $cluster.$proc@$schedd output"
echo "======="
if [ -r "/tmp/justin-wrapper-$cluster.$proc.$schedd.out" ] ; then
 cat "/tmp/justin-wrapper-$cluster.$proc.$schedd.out"
else
 echo '(missing - deleted?)'
fi
rm -f "/tmp/justin-wrapper-$cluster.$proc.$schedd.log" \
      "/tmp/justin-wrapper-$cluster.$proc.$schedd.out"
