#!/bin/sh
#
# Copyright 2013-23, Andrew McNab for the University of Manchester
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Script to allow interactive testing of Workflow System bootstrap scripts
# 1. Make sure you have rucio and metacat setup from cvmfs
# 2. Run this script with something like
#    bootwrap pfns-hello-world.bootstrap \
#     "files from dc4:dc4 where core.run_type='dc4-vd-coldbox-top' limit 1"
#    where "files from..." is an MQL expression for MetaCat
# 3. A temporary directory is created in /tmp and the bootstrap script is
#    run in the workspace subdirectory of that with outputs left there

export WFS_PATH=`mktemp -d /tmp/bootwrap.XXXXXX`
echo "Files created under $WFS_PATH"
echo

if [ ! -f "$1" ] ; then
 echo "Cannot find bootstrap script $1"
 exit 1
fi

cp "$1" $WFS_PATH/bootstrap.sh
bootstrap="$WFS_PATH/bootstrap.sh"
chmod +x $bootstrap

shift
mql="$*"
if [ "$mql" = "" ] ; then
  echo "You must give an MQL expression!"
  exit 2
fi

echo "Execute metacat query $mql | head -1"
did=`metacat query "$mql" | head -1`
if [ $? != 0 ] ; then
  echo "metacat query failed!"
  exit 3
fi

if [ "$did" = "" ] ; then
 echo "Need a DID"
 exit 4
fi

echo "Execute rucio list-file-replicas --pfns $did"
pfn=`rucio list-file-replicas --protocols root --pfns $did | head -1`
if [ "$pfn" = "" ] ; then
  echo "No PFN obtained from Rucio!"
  exit 5
fi

# Fake up the generic job environment
mkdir -p "$WFS_PATH/workspace"
echo "#!/bin/sh"           >$WFS_PATH/wfs-get-file
echo "echo $did $pfn XXX" >>$WFS_PATH/wfs-get-file
chmod +x $WFS_PATH/wfs-get-file

echo "====Start of bootstrap script execution===="
( cd $WFS_PATH/workspace ; stdbuf -oL -eL $WFS_PATH/bootstrap.sh ) 
echo "====End of bootstrap script execution===="

ls -lR "$WFS_PATH/workspace"
