#!/bin/sh
#
# Script to allow interactive testing of Workflow System bootstrap scripts
# 1. Make sure you have rucio and metacat setup from cvmfs
# 2. Create a directory and put your bootstrap script in it
# 3. Change to that directory and run this script with something like
#   ./bootwrap pfns-hello-world.bootstrap dc4-hd-protodune:dc4_np04hd_507141310_00497651-30da-41b5-90d2-2d5db7d57671-gen_protodunehd_1GeV_56895801_0_g4_detsim_a.root
#    where dc4-hd-... etc is the DID of a file registered in Rucio
#    (This will change to an MQL expression soon)
# 4. A workdir-TIMESTAMP subdirectory is created and the bootstrap script is
#    run in the workspace subdirectory of that and puts its outputs there
#

bootstrap="$PWD/$1"
chmod +x $bootstrap

if [ ! -x "$1" ] ; then
 echo "Cannot find executable bootstrap script $1 in this directory"
 exit 1
fi

# UNCOMMENT THIS ONCE METACAT IS ACCESSIBLE AGAIN
#shift
#mql="$*"
#if [ "$mql" = "" ] ; then
#  echo "You must give an MQL expression!"
#  exit 2
#fi
#
#echo "Execute metacat query $mql | head -1"
#did=`metacat query "$mql" | head -1`
#if [ $? != 0 ] ; then
#  echo "metacat query failed!"
#  exit 3
#fi

did="$2"
if [ "$did" = "" ] ; then
 echo "Need a DID"
 exit 3
fi

echo "Execute rucio list-file-replicas --pfns $did"
pfn=`rucio list-file-replicas --protocols root --pfns $did | head -1`
if [ "$pfn" = "" ] ; then
  echo "No PFN obtained from Rucio!"
  exit 4
fi

# Fake up the generic job environment
export WFS_PATH=$PWD/workdir-`date +'%s'`
mkdir -p "$WFS_PATH/workspace"
echo "#!/bin/sh"           >$WFS_PATH/wfs-get-file
echo "echo $did $pfn XXX" >>$WFS_PATH/wfs-get-file
chmod +x $WFS_PATH/wfs-get-file

echo "====Start of bootstrap script execution===="
( cd $WFS_PATH/workspace ; stdbuf -oL -eL $bootstrap ) 
echo "====End of bootstrap script execution===="

