#!/bin/sh
#
# Make bootstraps for DC4 from vdcoldbox-top.bootstrap
#

sed -e 's/top/bottom/g' \
    -e 's/^fclFile.*/fclFile=standard_reco_vdcb_48deg_bot.fcl/' \
 dc4-vd-coldbox-top.bootstrap > dc4-vd-coldbox-bottom.bootstrap

sed -e 's/dc4-vd-coldbox-top/dc4-hd-protodune/g' \
    -e 's/^fclFile.*/fclFile=protoDUNEHD_refactored_reco.fcl/' \
    -e 's/^export DUNEVERSION=.*/export DUNEVERSION=v09_56_00d00/' \
 dc4-vd-coldbox-top.bootstrap > dc4-hd-protodune.bootstrap
