#!/usr/bin/env python3
#
# metacat-rucio-to-sam - backfill SAM with files registered in MetaCat and
#                        Rucio
#
# Copyright 2013-23, Andrew McNab for the University of Manchester
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

import sys
import argparse

#
# PROGRAM MAIN !!!
# 

parser = argparse.ArgumentParser(prog='metacat-rucio-to-sam',
  usage='metacat-rucio-to-sam [OPTIONS]\n')
                                 
parser.add_argument("--mql",
                    type = str,
                    help = "MQL query")

parser.add_argument("--sam-query",
                    type = str,
                    help = "SAM query")

parser.add_argument("--count",
                    type = int,
                    help = "SAM declares per invocation")

try:
  args = vars(parser.parse_args())
except:
  sys.exit(1)

if not args['mql']:
  print('--mql missing', file=sys.stderr)
  sys.exit(1)

if not args['sam_query']:
  print('--sam-query missing', file=sys.stderr)
  sys.exit(1)

if not args['count']:
  print('--count missing', file=sys.stderr)
  sys.exit(1)

print(args)
