#!/bin/sh
#
# Script to set up components needed by justIN containers
#
# Tested on SL7.9
#

# Create the dunejustin account before anything else
useradd --uid 1026 --user-group dunejustin

echo 7.9 > /etc/yum/vars/releasever

# Ignore broken local repo
sed -i 's/^enabled.*/enabled=0/' /etc/yum.repos.d/nagios.repo

yum clean all

yum -y install ca_policy_igtf-classic git voms-clients-cpp 

(
cd /tmp
git clone https://github.com/DUNE/dune-justin.git
cp -f dune-justin/agents/justin-create-x509-proxies /etc/cron.daily/
cp -f dune-justin/agents/*.service dune-justin/services/*.service \
       /usr/lib/systemd/system/
)

systemctl enable justin-httpd justin-finder justin-job-factory justin-info-collector
 
mkdir -p /var/log/justin /var/run/justin /var/log/httpd /etc/letsencrypt /etc/vomses          

echo '"dune" "voms1.fnal.gov" "15042" "/DC=org/DC=incommon/C=US/ST=Illinois/O=Fermi Research Alliance/CN=voms1.fnal.gov" "dune"' >/etc/vomses/dune-voms1.fnal.gov
echo '"dune" "voms2.fnal.gov" "15042" "/DC=org/DC=incommon/C=US/ST=Illinois/O=Fermi Research Alliance/CN=voms2.fnal.gov" "dune"' >/etc/vomses/dune-voms2.fnal.gov


