.TH JUSTIN  "2024" "justin-rucio-upload" "justIN Manual"
.SH NAME
.B justin-rucio-upload
\- justIN utility to upload files with the Rucio upload API
.SH SYNOPSIS
.B justin-rucio-upload [--help] --rse RSE --scope SCOPE --dataset DATASET
.B [--protocol PROTOCOL] [--timeout SECONDS] [--tries TRIES] [--no-check]
.B PATH 
.SH DESCRIPTION
.B justin-rucio-upload
is a command-line utility to upload a file using Rucio's upload API which
provides more options than the 
.B rucio upload 
command. It is
used by justIN wrapper jobs to upload job outputs to Rucio managed storage.
You may find it useful for some debugging but it is not supported for 
end-users.

.SH OPTIONS

Apart from --help, none of the options are optional!

.HP 
.B "-h, --help"
.br
Show help message and exit.

.HP 
.B "--rse RSE"
.br
The name of the RSE. Required.

.HP 
.B "--scope SCOPE"
.br
The scope used for the uploaded file and the Rucio dataset to which it is
attached. Required.

.HP 
.B "--dataset DATASET"
.br
The name suffix of the dataset, without the scope. Required.

.HP 
.B "--protocol PROTOCOL"
.br
Optionally gives the protocol used for the upload: davs, root, etc.
Default davs.

.HP 
.B "--timeout SECONDS"
.br
Optional timeout in seconds to pass to Rucio. Default 60.

.HP 
.B "--tries TRIES"
.br
Optionally gives number of times to try each Rucio call. Default 1.

.HP 
.B "--no-check"
.br
Optionally prevents checking the Rucio the file has successfully been 
registered in Rucio with a replica and put in the given dataset.

.SH AUTHOR
Andrew McNab <Andrew.McNab@cern.ch>

.SH "SEE ALSO"
justin(1)
