.TH JUSTIN  "2023" "justin-test-jobscript" "justIN Manual"
.SH NAME
.B justin-test-jobscript
\- interactive testing of justIN jobscripts
.SH SYNOPSIS
.B justin-test-jobscript [--help] --jobscript FILENAME
.B --mql MQL [--env NAME=VALUE]
.SH DESCRIPTION
.B justin-test-jobscript
is a command-line utility to test jobscripts which normally run inside justIN 
jobs on the grid. The jobscripts are run with Apptainer 
using the same container format as for jobs, providing a very realistic
test. The options to the command have the same functions as the
corresponding options to the 
.B justin
command.

If the jobscript reads from remote storage, you need to have a valid DUNE
VOMS proxy when the 
.B justin-test-jobscript
command is run, either at /tmp/x509up_u`id -u` or in the location indicated
by $X509_USER_PROXY. A copy of the proxy is made and made available to the
jobscript inside the container via $X509_USER_PROXY.

The command displays the output of the jobscript while it is running and
then lists the files produced, which are left in the container's working
directory which you can examine.

.SH OPTIONS AND ARGUMENTS

.HP 
.B "-h, --help"
.br
Show help message and exit.

.HP 
.B "--jobscript FILENAME"
.br
Filename of the jobscript to be tested.

.HP 
.B "--mql MQL"
.br
MetaCat MQL expression use to find input files. 
.B justin-test-jobscript
uses the 
.B justin show-replicas
command to find the replicas using MetaCat and Rucio queries by the justIN
service.

.HP 
.B "--env NAME=VALUE"
.br
This option can be used one or more times to define environment variables 
which will be set inside the container. 

.SH EXAMPLE

In this example we make a local copy of a jobscript from the Jobscripts
Library and then run it using the
.B justin-test-jobscript
command, using the jobscript's $NUM_EVENTS variable to limit processing to
the first event of the input file.

.nf 
justin show-jobscript --jobscript-id dc4-vd-coldbox-top:default \\
  > my-dc4-vd-coldbox-top.jobscript

justin-test-jobscript --mql \\
 "files from dc4:dc4 where core.run_type='dc4-vd-coldbox-top' limit 10" \\
 --jobscript my-dc4-vd-coldbox-top.jobscript \\
 --env NUM_EVENTS=1

.fi

.SH AUTHOR
Andrew McNab <Andrew.McNab@cern.ch>

.SH "SEE ALSO"
justin(1)
