.TH JUSTIN  "2024" "justin-cvmfs-upload" "justIN Manual"
.SH NAME
.B justin-cvmfs-upload
\- upload files to cvmfs via RCDS for justIN
.SH SYNOPSIS
.B justin-cvmfs-upload [--help] [--verbose] TAR_FILE
.SH DESCRIPTION
.B justin-cvmfs-upload
is a command-line utility for uploading one or more files contained in a tar
archive file to cvmfs using the Fermilab Rapid Code Distribution Service 
(RCDS). The full cvmfs path is then output by the command.

The environment variable 
.B JOBSUB_DROPBOX_SERVER_LIST 
is used to find a random RCDS server to use, or 
.B rcds01.fnal.gov
if the variable is not set.

.SH OPTIONS AND ARGUMENTS

.HP 
.B "-h, --help"
.br
Show help message and exit.

.HP 
.B "-v, --verbose"
.br
Turn on verbose logging.

.HP 
.B "TAR_FILE"
.br
A .tar archive file (not a tar.tgz compressed archive!) containing files to
be uploaded to cvmfs via RCDS.

.SH EXAMPLE

.B justin-cvmfs-upload
must be run on a computer inside the Fermilab firewall. You also need a 
valid Bearer Token at $BEARER_TOKEN_FILE if set or
/run/users/UID/bt_uUID if it exists or
/tmp/bt_uUID in other cases, where UID is your local Unix user ID, which 
you can create with the command 
.B justin get-token

.nf
htgettoken -a htvaultprod.fnal.gov -i dune
mkdir somedir
cd somedir
date > hello_world.txt
tar cvf hello_world.tar *
INPUT_TAR_DIR_LOCAL=`justin-cvmfs-upload hello_world.tar`
echo $INPUT_TAR_DIR_LOCAL
.fi

.SH AUTHOR
Andrew McNab <Andrew.McNab@cern.ch>

.SH "SEE ALSO"
justin(1)
