#!/bin/sh

if [ "$1" = "" ] ; then
 echo 'Must give the JSON file!'
 exit 1
fi

export USERID=`id -u`
export X509_USER_PROXY=${X509_USER_PROXY:-/tmp/x509up_u$USERID}

curl \
--key $X509_USER_PROXY \
--cert $X509_USER_PROXY \
--cacert $X509_USER_PROXY \
--capath ${X509_CERTIFICATES:-/etc/grid-security/certificates/} \
--data @$1 \
--output ${2:--} \
--write-out "%{http_code}\n" \
https://wfs-dev.dune.hep.ac.uk/wfa-cgi

