.TH WORKFLOW  "2021" "workflow" "WFS Manual"
.SH NAME
.B workflow
\- Workflow System utility command
.SH SYNOPSIS
.B workflow subcommand [options]
.SH DESCRIPTION
.B workflow
is a command-line utility for managing requests, stages, files, and replicas
in the Workflow System Database (WFDB).

.SH GENERAL OPTIONS

.HP 
.B "-h, --help"
.br
Show help message and exit

.HP 
.B "-v, --verbose"
.br
Turn on verbose logging of the communication with the WFDB service.

.HP 
.B "--url URL"
.br
Use an alternative Worklow Service, rather than 
https://wfs-pro.dune.hep.ac.uk/wfdb-cgi This 
option is only needed during development and testing.

.SH SUBCOMMANDS

.HP
.B "version"
.br
Output the version number of the workflow command.

.HP
.B "create-request [--name NAME] [--mql QUERY|--monte-carlo COUNT] [--refind-start YYYYMMDD] [--refind-end YYYYMMDD] [--refind-hours HOURS]"
.br
Create a new, empty request in the database, optionally with the given 
human-readable name and either a MetaCat Query Language expression or
the count of the number of Monte Carlo instances to run. If a name is not 
given, a name based on a timestamp is created. 
Requests are created in the state "draft" and the command returns the new 
request's ID number.
Once the request is in the running state, the Workflow System will use the 
MQL expression to find the list of input files from MetaCat. If 
.B --refind-hours
is given, the MQL query will be resubmitted at that interval to add any
new matching files from the start of the day given by
.B --refind-start
(default: today in UTC) to the end of the day given by
.B --refind-end
(default: today in UTC).

.HP
.B "show-requests [--request-id ID]"
.br
Show details of all requests or optionally of a single request. Each line
of the output gives the request ID, state, creation time, name, and MetaCat
query of one request.

.HP
.B "submit-request --request-id ID"
.br
.B Currently not used. 
Changes the state of the given request from "draft" to "submitted". In the 
future, this
will allow automated sanity checking and prioritisation of requests. For 
very large requests it may give an opportunity for manual approval by the 
operations team.

.HP
.B "start-request --request-id ID"
.br
Starts a request in the "draft" or "submitted" state or restarts a request
in the "paused" stated, and changes its state to "running".

.HP
.B "pause-request --request-id ID"
.br
Changes the state of the given request to "paused". This state temporarily
excludes a request from the workflow allocation process.

.HP
.B "finish-request --request-id ID"
.br
Changes the state of the given request to "finished". This state 
excludes a request from the workflow allocation process.

.HP
.B "create-stage --request-id ID --stage-id ID --file FILENAME [--wall-seconds N] [--rss-bytes N] [--processors N] [--max-distance DIST] [--output-pattern DATASET-SCOPE:DATASET-NAME:SCOPE:PATTERN] [--output-pattern-next-stage DATASET-SCOPE:DATASET-NAME:SCOPE:PATTERN] [--output-rse NAME]" 
.br
Creates a new stage for the given request ID with the given stage ID. Stages
must be numbered consecutively from 1, and each request must have at least
one stage. Each stage must have a boostrap shell script associated with it,
given by the
.B --file
option which will be executed on worker nodes to process its files. 

If the maximum wallclock time needed is not given by 
.B --wall-seconds
then the default of 80000
seconds is used. If the maximum amount of resident memory needed is not
given by 
.B --rss-mb
then the default of 2048MiB is used. The resident memory corresponds to the 
physical memory managed by HTCondor's ResidentSetSize value.

If the script can make use of multiple processors then 
.B --processors
can be used to give the number needed, with a default of 1 if not given.

By default, input files will only be allocated to a script which are on 
storages at the same site (distance=0). This can be changed by setting
.B --max-distance DIST
to allow input files to be allocated on storages at greater distances, up to
a value of 100 which represents maximally remote storages.

If one or more options 
.B --output-pattern DATASET-SCOPE:DATASET-NAME:SCOPE:PATTERN
is given then the generic job will look for files created by the script
which match the pattern given as PATTERN. The pattern is a Bash 
shell pattern using *, ? and
[...] expressions. See the bash(1) Pattern Matching section for details. Any
output files found by this matching will be uploaded and registered by the
generic job in the Rucio dataset given by DATASET-SCOPE:DATASET-NAME, with a 
DID composed of the scope given and the found filename. Furthermore, if the 
found files have a corresponding JSON metadata
file with the same name but with ".json" appended, that will be recorded for
that file in MetaCat.

Alternatively
.B --output-pattern-next-stage DATASET-SCOPE:DATASET-NAME:SCOPE:PATTERN
can be given in which the output file will also be registered in the
Workflow Database as an unprocessed input file for the next stage and
available for allocation to instances of that stage's script.

If one or more options
.B --output-rse NAME
is given, then the RSE used for uploads of output files will be chosen
from that list of RSEs, with preference given to RSEs which are closer in 
distance. If this option is not used, or none of the given RSEs are available,
then the default algorithm for choosing the closest available RSE is used.

.HP
.B "quick-request [--name NAME] [--mql QUERY|--monte-carlo COUNT] [--refind-start YYYYMMDD] [--refind-end YYYYMMDD] [--refind-hours HOURS] --file FILENAME [--wall-seconds N] [--rss-bytes N] [--processors N] [--max-distance DIST] [--output-pattern DATASET-SCOPE:DATASET-NAME:SCOPE:PATTERN] --output-rse NAME"
.br
Combines the 
.B create-request, create-stage
and
.B start-request
subcommands into a single operation, for use with single-stage requests.

.HP
.B "show-stages --request-id ID [--stage-id ID]"
.br
Shows details of all stages of the given request or optionally of a single 
stage of that request. Each line
of the output gives the request ID, stage ID,, min processors,
max processors, max wallclock seconds, max RSS bytes, and the max distance
value.

.HP
.B "show-bootstrap --request-id ID --stage-id ID"
.br
Show the bootstrap script of the given stage within the given request.

.HP
.B "show-stage-outputs --request-id ID --stage-id ID"
.br
Shows the datasets to be assigned and the patterns used to find output files 
of the given stage within the 
given request. Each line of the response consists of "(next)" or "(  )" 
depending on whether the files are passed to the next stage within the
request, and then the dataset, scope, and files pattern themselves.

.HP
.B "show-storages [--rse-name NAME]"
.br
Shows information about Rucio Storage Elements cached in the Workflow
Database, optionally limiting output to a single RSE using its name. Each
line of the output consists of the RSE name followed by the occupancy
fraction obtained from Rucio in the range 0.0 to 1.0, and the Read, Write
and Delete availability of the RSE from Rucio, and whether the RSE will be
included in the default list for output files.

.HP
.B "show-sites-storages [--site-name NAME] [--rse-name NAME]"
.br
Shows information about the distances of Rucio storage elements relative to
sites, optionally limited to the given site and/or RSE. Each line of the
output gives the site name, RSE name, and then their relative distance
between 0 (same site) and 100 (maximally remote).

.HP
.B "add-file --request-id ID [--stage-id ID] --file-did DID --rse-name NAME --pfn URL"
.br
Adds one file to the list of files to be processed in a stage, with the
given Rucio file Data Identifier (DID). 
.B Normally this should only be done for the first stage, 
which is the default. Files are created in the "unallocated" state, ready
for processing. Exactly RSE which has a replica of the file must be
given along with one PFN to access the replica on that RSE. This subcommand is
only intended for testing, as normally the Finder agent builds the lists of 
files and replicas for the first stage of a request using MetaCat and Rucio.

.HP
.B "show-files [--request-id ID] [--stage-id ID] [--file-did DID]"
.br
Shows files information cached in the Workflow Database, either limited by 
request ID and stage ID or by file DID. For each file, the request ID, stage
ID, file state, and file DID are shown. The file state is one of "finding",
"unallocated", "allocated", or "processed". Files wait in the "unallocated"
state, are then allocated to an instance of the stage's script by the 
Workflow Allocator, and then either return to "unallocated" or move to
"processed" depending on whether the script is able to process them
correctly.

.HP
.B "show-replicas [--request-id ID] [--stage-id ID] [--file-did DID]"
.br
Shows file and replica information in the Workflow Database, either limited by 
request ID and stage ID or by file DID. For each replica of each file, the 
request ID, stage ID, file state, RSE name, and file DID are shown. 

.HP
.B "show-jobs --jobsub-id ID | --request-id ID [--stage-id ID] [--state STATE]"
.br
Show jobs identified by Jobsub ID or Request ID (and optionally Stage ID). Job 
state can also be given to further filter the jobs listed. For each job,
the Jobsub ID, Request ID, Stage ID, State, and creation time are shown.

.SH REQUEST PROCESSING

Once a request enters the running state, it is processed by the Workflow 
System's Finder agent. Usually this is just done once, but it can be
repeated if the --refind-days option is given when creating the request.
When the request is processed, the Finder uses the requests's MQL 
expression to create a list of input files for the first stage. Work is only
assigned to jobs when a matching file is found and so these lists of files 
are essential.

In most cases, the MQL query is a MetaCat Query Language expression, which the
Finder sends to the MetaCat service to get a list of matching file DIDs.
However, if the query is of the form "rucio-dataset SCOPE:NAME" then the
query is sent directly to Rucio to get the list of file DIDs contained in
the given Rucio dataset. Finally if the 
.B --monte-carlo COUNT
option is used when creating the request, then an MQL of the form
"monte-carlo COUNT" is stored. This causes the Finder itself to create a
series of COUNT placeholder files which can be used to keep track of Monte
Carlo processing without a distinct input file for each of the COUNT jobs.
Each of these placeholder files has a DID of the form 
monte-carlo-REQUEST_ID-NUMBER where
NUMBER is in the range 1 to COUNT, and REQUEST_ID is the assigned request ID
number. 

.SH FILES

An X.509 user proxy file is currently needed to contact the Workflow Service,
which is either given by 
.B $X509_USER_PROXY 
or 
.B /tmp/x509up_uUSERID
where 
.B USERID
is the numeric Unix user id, given by 
.B id -u

.SH AUTHOR
Andrew McNab <Andrew.McNab@cern.ch>

.SH "SEE ALSO"
bash(1)
