#!/usr/bin/env python3
#
#  workflow - DUNE WFS command line utility
#
#  See the workflow(1) man page for full usage. 
#  For example with the command  man ./workflow.1 
#
#  Andrew McNab, University of Manchester.
#  Copyright (c) 2013-21. All rights reserved.
#
#  Redistribution and use in source and binary forms, with or
#  without modification, are permitted provided that the following
#  conditions are met:
#
#    o Redistributions of source code must retain the above
#      copyright notice, this list of conditions and the following
#      disclaimer. 
#    o Redistributions in binary form must reproduce the above
#      copyright notice, this list of conditions and the following
#      disclaimer in the documentation and/or other materials
#      provided with the distribution. 
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
#  CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
#  INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
#  DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
#  BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
#  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
#  TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
#  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
#  ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
#  OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
#  OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.

import os
import sys
import json
import ssl
import urllib.request
import argparse

versionString = 'Workflow 0.1 (urllib)'

def body(buf): 

  sys.stdout.write(buf.decode('UTF-8'))

#
# PROGRAM MAIN !!!
# 

parser = argparse.ArgumentParser()

commands = [ "create-request", 
             "submit-request", 
             "start-request",
             "add-file",
             "pause-request",
             "create-stage", 
             "quick-request", 
             "create-storage",
             "create-site-storage",
             "show-requests", "show-stages", "show-bootstrap",
             "show-stage-outputs",
             "show-files", "show-replicas", "show-storages",
             "show-sites-storages", "show-jobs" ]

parser.add_argument("command",
                    type = str,
                    help = "Workflow command to execute: " +
                           ' '.join(commands) )

parser.add_argument("-v", 
                    "--verbose",
                    action = "store_true",
                    help = "Verbose logging")

parser.add_argument("--request-id",
                    type = int,
                    help = "Request ID number")

parser.add_argument("--stage-id",
                    type = int,
                    help = "Stage ID number")

parser.add_argument("--file-did",
                    type = str,
                    help = "File DID")

parser.add_argument("--site-name",
                    type = str,
                    help = "Site name")

parser.add_argument("--rse-name",
                    type   = str,
                    action = "append",
                    help   = "RSE name")

parser.add_argument("--name",
                    type = str,
                    help = "Name to assign")

parser.add_argument("--mql",
                    type = str,
                    help = "MetaCat Query")

parser.add_argument("--monte-carlo",
                    type = int,
                    help = "Monte Carlo count")

parser.add_argument("--refind-days",
                    type = float,
                    help = "Refind interval in days")

parser.add_argument("--refind-limit-days",
                    type = float,
                    help = "Refind duration in days")

parser.add_argument("--upload-file",
                    type = str,
                    help = "Specify a local file")

parser.add_argument("--processors",
                    type = int,
                    help = "Number of processors required")

parser.add_argument("--wall-seconds",
                    type = int,
                    help = "Maximum wall seconds")

parser.add_argument("--rss-mb",
                    type = float,
                    help = "Maximum RSS MiB")

parser.add_argument("--max-distance",
                    type = float,
                    help = "Max distance for reading from storage")

parser.add_argument("--output-pattern",
                    type   = str,
                    action = "append",
                    help   = "Output files pattern")

parser.add_argument("--output-pattern-next-stage",
                    type   = str,
                    action = "append",
                    help   = "Output files for next stage pattern")

parser.add_argument("--output-rse",
                    type   = str,
                    action = "append",
                    help   = "Name of RSE to use for output files")

parser.add_argument("--pfn",
                    type   = str,
                    action = "append",
                    help   = "PFN of a replica")

parser.add_argument("--jobsub-id",
                    type = str,
                    help = "Jobsub ID number")

parser.add_argument("--state",
                    type = str,
                    help = "Restrict output by state")

parser.add_argument("--url",
                    type = str,
                    help = "WFS service to contact")

args = parser.parse_args()
jsonDict = vars(args)

if jsonDict['upload_file']:
  with open(jsonDict['upload_file']) as f:
    jsonDict['file'] = f.read()

if args.command not in commands:
  print("%s not recognised as a workflow command" % args.command)
  sys.exit(1)

if jsonDict['verbose']:
  print(jsonDict)

# Set up request contexts to send the command to the WFS

if jsonDict['url']:
  url = jsonDict['url']
else:
  url = 'https://wfs-pro.dune.hep.ac.uk/wfdb-cgi'

httpRequest = urllib.request.Request(url,
                                     data = json.dumps(jsonDict).encode(),
                                     method = 'POST')

sslContext = ssl.SSLContext()

if 'X509_USER_PROXY' in os.environ and os.environ['X509_USER_PROXY']:
  sslContext.load_cert_chain(os.environ['X509_USER_PROXY'])
else:
  sslContext.load_cert_chain('/tmp/x509up_u%d' % os.getuid())

if 'X509_CERTIFICATES' in os.environ and os.environ['X509_CERTIFICATES']:
  sslContext.load_verify_locations(capath = os.environ['X509_CERTIFICATES'])
else:
  sslContext.load_verify_locations(capath = '/etc/grid-security/certificates')

try:
  response = urllib.request.urlopen(httpRequest, context = sslContext)
except urllib.error.URLError as e:
  print(e.read().decode('utf-8'), end='')
  sys.exit(21)
  
if response.status != 200:
  if jsonDict['verbose']:
    print(response.read().decode('utf-8'), end='')
  sys.exit(20)
  
print(response.read().decode('utf-8'), end='')
sys.exit(0)
