#!/usr/bin/env python3
#
# execute-generic-job - run the generic job script interactively for testing
#
# Copyright 2013-23, Andrew McNab for the University of Manchester
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

import os
import time
import secrets
import tempfile
import subprocess

# Needs MySQL-python RPM
import MySQLdb

# justin/conf.py must define these variables in a way that is both
# valid Python and valid Bash!
#
# mysqlUser='username'
# mysqlPassword='PAsSWoRd'
#
import justin

rawJob = open('/var/lib/justin/justin-generic-job-py','r').read()

processedJob = rawJob.replace('###justin_job_secret###',
                              secrets.token_urlsafe(64))

f = tempfile.NamedTemporaryFile(mode='w', delete=False)

f.write(processedJob)

tempJobFile = f.name

f.close()

os.chmod(tempJobFile, 0o700)

jobEnv = { 'PATH'            : '/usr/bin',
           'GLIDEIN_DUNESite': 'US_FNAL',
           'JOBSUBJOBID'     : str(int(time.time())) + '@execute-generic-job'
         }

subprocess.run(tempJobFile, env=jobEnv)

