#!/bin/sh

source /cvmfs/grid.cern.ch/centos7-ui-200122/etc/profile.d/setup-c7-ui-example.sh
source /cvmfs/dune.opensciencegrid.org/products/dune/setup_dune.sh
setup jobsub_client v1_3_5
setup cigetcert
#export X509_USER_PROXY=/var/lib/justin/justin-jobs-production.proxy.pem

jobsub_rm \
  --debug \
  --user dunepro \
  --constraint \
  '(regexp("justin-generic-job$",TransferInput) && JobStatus=?=1 && EnteredCurrentStatus < (CurrentTime - 7*86400))'

sed "s/###justin_job_secret###/$6/g" /var/lib/justin/justin-generic-job \
 >/var/lib/justin/justin-generic-job.tmp

if [ "$2" = "FNAL_GPGrid" ] ; then
 jobsub_submit \
  --debug \
  -N ${1} \
  --memory ${3}KB \
  --cpu ${4} \
  --expected-lifetime=${5}s \
  --group dune \
  --subgroup prod_keepup \
  --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC \
  --lines '+SingularityImage=\"/cvmfs/singularity.opensciencegrid.org/fermilab/fnal-wn-sl7:osg3.6\"' \
  file:///var/lib/justin/justin-generic-job.tmp 2>/dev/null
elif [ "$2" = "ANY" -o "$2" = "NOT_FNAL_GPGrid" ] ; then
 if [ "$7" != "" ] ; then
   blacklist_option="--blacklist $7"
 fi

 if [ "$2" = "NOT_FNAL_GPGrid" ] ; then
   USAGE_MODEL='OFFSITE'
 else
   USAGE_MODEL='OFFSITE,DEDICATED,OPPORTUNISTIC'
 fi

 jobsub_submit \
  --debug \
  -N ${1} \
  --memory ${3}KB \
  --cpu ${4} \
  --expected-lifetime=${5}s \
  --group dune \
  --subgroup prod_keepup \
  --resource-provides=usage_model="$USAGE_MODEL" \
  --lines '+SingularityImage=\"/cvmfs/singularity.opensciencegrid.org/fermilab/fnal-wn-sl7:osg3.6\"' \
  "$blacklist_option" \
  file:///var/lib/justin/justin-generic-job.tmp 2>/dev/null
else
 jobsub_submit \
  --debug \
  -N ${1} \
  --site ${2} \
  --memory ${3}KB \
  --cpu ${4} \
  --expected-lifetime=${5}s \
  --group dune \
  --subgroup prod_keepup \
  --resource-provides=usage_model=OFFSITE \
  --lines '+SingularityImage=\"/cvmfs/singularity.opensciencegrid.org/fermilab/fnal-wn-sl7:osg3.6\"' \
  file:///var/lib/justin/justin-generic-job.tmp 2>/dev/null
fi
