#!/bin/sh

source /cvmfs/grid.cern.ch/centos7-ui-200122/etc/profile.d/setup-c7-ui-example.sh
source /cvmfs/dune.opensciencegrid.org/products/dune/setup_dune.sh
setup jobsub_client v1_3_5
setup cigetcert
export X509_USER_PROXY=/var/lib/justin/justin-jobs-production.proxy.pem

if [ "$2" = "FNAL_GPGrid" ] ; then
 jobsub_submit \
  --debug \
  -N ${1} \
  --memory ${3}KB \
  --cpu ${4} \
  --expected-lifetime=${5}s \
  --group dune \
  --subgroup prod_keepup \
  --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC \
  --lines '+SingularityImage=\"/cvmfs/singularity.opensciencegrid.org/fermilab/fnal-wn-sl7:latest\"' \
  file:///var/lib/justin/justin-generic-job 2>/dev/null
elif [ "$2" = "ANY" ] ; then
 if [ "$6" != "" ] ; then
   blacklist_option="--blacklist $6"
 fi

 jobsub_submit \
  --debug \
  -N ${1} \
  --memory ${3}KB \
  --cpu ${4} \
  --expected-lifetime=${5}s \
  --group dune \
  --subgroup prod_keepup \
  --resource-provides=usage_model=OFFSITE,DEDICATED,OPPORTUNISTIC \
  --lines '+SingularityImage=\"/cvmfs/singularity.opensciencegrid.org/fermilab/fnal-wn-sl7:latest\"' \
  "$blacklist_option" \
  file:///var/lib/justin/justin-generic-job 2>/dev/null
else
 jobsub_submit \
  --debug \
  -N ${1} \
  --site ${2} \
  --memory ${3}KB \
  --cpu ${4} \
  --expected-lifetime=${5}s \
  --group dune \
  --subgroup prod_keepup \
  --resource-provides=usage_model=OFFSITE \
  --lines '+SingularityImage=\"/cvmfs/singularity.opensciencegrid.org/fermilab/fnal-wn-sl7:latest\"' \
  file:///var/lib/justin/justin-generic-job 2>/dev/null
fi
