#!/bin/sh

source /cvmfs/grid.cern.ch/centos7-ui-200122/etc/profile.d/setup-c7-ui-example.sh
source /cvmfs/dune.opensciencegrid.org/products/dune/setup_dune.sh
setup jobsub_client
setup cigetcert

if [ "$2" = "FNAL_GPGrid" ] ; then
 jobsub_submit \
  --debug \
  -N ${1} \
  --memory ${3}KB \
  --cpu ${4} \
  --expected-lifetime=${5}s \
  --group dune \
  --subgroup prod_keepup \
  --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC \
  file:///var/lib/wfs/wfs-generic-job 2>/dev/null
else
 jobsub_submit \
  --debug \
  -N ${1} \
  --site ${2} \
  --memory ${3}KB \
  --cpu ${4} \
  --expected-lifetime=${5}s \
  --group dune \
  --subgroup prod_keepup \
  --resource-provides=usage_model=OFFSITE \
  file:///var/lib/wfs/wfs-generic-job 2>/dev/null
fi
