#!/bin/sh
#
# Run the rucio command in an environment with Python3 and the required 
# modules already installed in $WFS_PATH/wfs-rucio-local
#
# This script must be converted to base64 with something like the following 
# and included in the here document near the start of wfs-generic-job :
#
# (macOS) base64 -b 76 wfs-rucio > wfs-rucio.b64
# (Linux) base64       wfs-rucio > wfs-rucio.b64
#

export WFS_RUCIO_LOCAL=$WFS_PATH/wfs-rucio-local
export PYTHONPATH="$WFS_RUCIO_LOCAL/lib/python3.8/site-packages"

exec $WFS_RUCIO_LOCAL/bin/rucio --timeout 60 \
  --config $WFS_RUCIO_LOCAL/etc/rucio.cfg $*
