version: '3'

networks:
  internal:
volumes:
  maria-db:

services:
  justin:
    build:
      context: ..
      dockerfile: docker/justin/Dockerfile    
    volumes:
      - ./services/rucio.cfg:/opt/rucio/etc/rucio.cfg
    networks:
      internal:
        aliases:
          - justin
