#!/bin/sh
#
# Temporary script to initialise the Workflow Database with some values
# which wfs-info-collector cannot discover itself
#
# Creates wfdb-populate.sql which can be fed straight into the mysql command
# AFTER wfs-info-collector HAS RUN ONCE
#

(

UK_STORAGES="EDINBURGH IMPERIAL LANCASTER LIVERPOOL MANCHESTER QMUL"
UK_STORAGES="$UK_STORAGES RAL_ECHO RAL-PP"

EURO_STORAGES="$UK_STORAGES CERN_PDUNE_EOS DUNE_ES_PIC DUNE_FR_CCIN2P3"
EURO_STORAGES="$EURO_STORAGES DUNE_FR_CCIN2P3_DISK DUNE_FR_CCIN2P3_XROOTD"
EURO_STORAGES="$EURO_STORAGES NIKHEF PRAGUE"

US_STORAGES="DUNE_US_BNL_SDCC FNAL_DCACHE FNAL_DCACHE_PERSISTENT"
US_STORAGES="$US_STORAGES FNAL_DCACHE_STAGING FNAL_DCACHE_TEST T3_US_NERSC"

echo 
echo '# European sites sites and storages are at distance 3.0'
RSE_NAME_TEST="FALSE"
for i in $EURO_STORAGES
do
  RSE_NAME_TEST="$RSE_NAME_TEST OR rse_name='$i'"
done

echo "UPDATE sites_storages SET distance=3.0 WHERE "
echo " (SELECT site_name FROM sites "
echo "  WHERE sites.site_id=sites_storages.site_id) "
echo "  RLIKE '^CERN|^CH_|^CZ_|^ES_|^FR_|^NL|^UK_'"
echo " AND site_storages.rse_id IN "
echo "  (SELECT rse_id FROM storages WHERE $RSE_NAME_TEST);"

echo
echo '# UK_**** sites and UK storages are at distance 2.0'
echo '# This will overwrite some of the 3.0 distances set above'
RSE_NAME_TEST="FALSE"
for i in $UK_STORAGES
do
  RSE_NAME_TEST="$RSE_NAME_TEST OR rse_name='$i'"
done

echo "UPDATE sites_storages SET distance=2.0 WHERE "
echo " (SELECT site_name FROM sites "
echo "  WHERE sites.site_id=sites_storages.site_id) RLIKE '^UK_'"
echo " AND site_storages.rse_id IN "
echo "  (SELECT rse_id FROM storages WHERE $RSE_NAME_TEST);"

echo
echo '# US_**** and CA_**** sites and US storages are at distance 2.0'
RSE_NAME_TEST="FALSE"
for i in $US_STORAGES
do
  RSE_NAME_TEST="$RSE_NAME_TEST OR rse_name='$i'"
done

echo "UPDATE sites_storages SET distance=2.0 WHERE "
echo " (SELECT site_name FROM sites "
echo "  WHERE sites.site_id=sites_storages.site_id) RLIKE '^US_|^CA_'"
echo " AND site_storages.rse_id IN "
echo "  (SELECT rse_id FROM storages WHERE $RSE_NAME_TEST);"

echo
echo '# Sites which have storages nearby get distance 1.0'
(
cat <<EOF
UK_RAL-PPD RAL_ECHO
UK_RAL-Tier1 RAL_PPD
EOF
) | (
while read site rse
do
  echo "REPLACE INTO sites_storages SET "
  echo " site_id=(SELECT site_id FROM sites WHERE site_name='$site'),"
  echo " rse_id=(SELECT rse_id FROM storages WHERE rse_name='$rse'),"
  echo " distance=1.0;"
done
)

echo
echo '# Sites which have storages on site get distance 0.0'
(
cat <<EOF
CERN CERN_PDUNE_EOS
CZ_FZU PRAGUE
ES_PIC DUNE_ES_PIC
FR_CCIN2P3 DUNE_FR_CCIN2P3
FR_CCIN2P3 DUNE_FR_CCIN2P3_DISK
FR_CCIN2P3 DUNE_FR_CCIN2P3_XROOTD
NL_NIKHEF NIKHEF
UK_Edinburgh EDINBURGH
UK_Imperial IMPERIAL
UK_Liverpool LIVERPOOL
UK_Lancaster LANCASTER
UK_Manchester MANCHESTER
UK_QMUL QMUL
UK_RAL-Tier1 RAL_ECHO
UK_RAL-PPD RAL_PPD
US_BNL DUNE_US_BNL_SDCC
US_FNAL FNAL_DCACHE
US_FNAL FNAL_DCACHE_PERSISTANT
US_FNAL FNAL_DCACHE_STAGING
US_FNAL FNAL_DCACHE_TEST
EOF
) | (
while read site rse
do
  echo "REPLACE INTO sites_storages SET "
  echo " site_id=(SELECT site_id FROM sites WHERE site_name='$site'),"
  echo " rse_id=(SELECT rse_id FROM storages WHERE rse_name='$rse'),"
  echo " distance=0.0;"
done
)

) > wfdb-populate.sql
