#!/bin/sh

mysql -u root -p --batch --skip-column-names --execute "SELECT CONCAT(site_name,',',rse_name,',',distance) FROM sites_storages LEFT JOIN sites ON sites.site_id=sites_storages.site_id LEFT JOIN storages ON storages.rse_id=sites_storages.rse_id ORDER BY site_name,rse_name" wfdb >dune-site-storages.csv
