#!/usr/bin/env python3
#
# justin-registration - justIN Registration Agent
#
# Copyright 2013-26, Andrew McNab for the University of Manchester
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

import os
import sys
import ssl
import stat
import json
import time
import base64
import hashlib
import tempfile
import subprocess
import urllib.request
import pathlib
import xml.dom.minidom

## Needs MySQL-python RPM
#import MySQLdb

# WE NEED TO REMOVE OLD MySQLdb REFERENCES STILL!
import pymysql
pymysql.install_as_MySQLdb()
MySQLdb=pymysql

# Installed by pip3 install of Rucio
import rucio.client
import metacat.webapi

import justin

sleepSeconds         = 60
maxFilesPerBulk      = 500
minFilesPerBulk      = 1

clientMetaCat        = None
didClientRucio       = None
repClientRucio       = None
ruleClientRucio      = None

class justinError(Exception):
  pass

def getWorkflowsDatasets():
  # Return a list of all created datasets for all running wofklows
  
  try:
    query = ('SELECT dataset_name,scopes.scope_name '
             'FROM workflows_datasets '
             'LEFT JOIN workflows '
             'ON workflows.workflow_id=workflows_datasets.workflow_id '
             'LEFT JOIN scopes '
             'ON workflows.scope_id=scopes.scope_id '
             'WHERE workflow_state="running"')
             
    rows = justin.select(query)
             
  except Exception as e:
    justin.logLine('Failed to get list of datasets: ' + str(e))
    return {}
    
  datasetsList = []
  for row in rows:
    datasetsList.append(row['scope_name'] + ':' + row['dataset_name'])
    
  return datasetsList    
  
def findFinishingJobs():
  # Find jobs in the finishing state, register their output files, and mark
  # jobs as finished
  
  justin.logLine('Start of finding finishing jobs')

  existingDatasets = getWorkflowsDatasets()
  if not existingDatasets:
    return

  # Find finishing jobs and their output files
  # We limit this to maxFilesPerBulk + 1 to get the start of the next
  # job's files to detect the end of the last job we actually want
  try:
    query = ('SELECT jobs.justin_job_id,files.file_id,replica_id,destination,'
             'file_metadata,number_in_pattern,scope_name,files.file_did,'
             'stages_outputs.lifetime_seconds,jobs.workflow_id,jobs.stage_id,'
             'stages_outputs.pattern_id,files.size_bytes,rse_name,adler32 '
             'FROM jobs '
             'LEFT JOIN workflows ON workflows.workflow_id=jobs.workflow_id '
             'LEFT JOIN scopes ON scopes.scope_id=workflows.scope_id '
             'LEFT JOIN files '
             'ON files.creator_justin_job_id=jobs.justin_job_id '
             'AND files.file_state="registering" '
             'LEFT JOIN replicas '
             'ON files.file_id=replicas.file_id '
             'LEFT JOIN storages '
             'ON storages.rse_id=replicas.rse_id '
             'LEFT JOIN stages_outputs '
             'ON files.workflow_id=stages_outputs.workflow_id '
             'AND files.creator_stage_id=stages_outputs.stage_id '
             'AND files.creator_pattern_id=stages_outputs.pattern_id '
             'WHERE job_state="finishing" AND files.file_id<>NULL '
             'AND replicas.replica_id<>NULL '
             'ORDER BY justin_job_id,file_id '
             'LIMIT %d' % (maxFilesPerBulk + 1))

    jobsFilesRows = justin.select(query)
  except Exception as e:
    justin.logLine('Failed to get list of finishing jobs/files: ' + str(e))
    return

  # Get output files from jobs, grouped by job so each job's files' 
  # registrations are all or none so we can fail whole jobs to force retries

  jobsList           = []
  jobDict            = {}
  numFiles           = 0
  currentJustinJobId = 0
  
  for jobFileRow in jobsFilesRows:
  
    if jobFileRow['justin_job_id'] != currentJustinJobId:
      # Save previous job dict
      if jobDict:
        jobsList.append(jobDict)

      # Create new job dict
      jobDict = { 'justin_job_id' : jobFileRow['justin_job_id'], 
                  'workflow_id'   : jobFileRow['workflow_id'],
                  'stage_id'      : jobFileRow['stage_id'],
                  'pattern_id'    : jobFileRow['pattern_id'],
                  'scope_name'    : jobFileRow['scope_name'],
                  'files_list' : [] }

    jobDict['files_list'].append(
       { 'file_id'           : jobFileRow['file_id'],
         'file_did'          : jobFileRow['file_did'],
         'replica_id'        : jobFileRow['replica_id'],
         'lifetime_seconds'  : jobFileRow['lifetime_seconds'],
         'size_bytes'        : jobFileRow['size_bytes'],
         'adler32'           : jobFileRow['adler32'],
         'rse_name'          : jobFileRow['rse_name'],
         'destination'       : jobFileRow['destination'],
         'file_metadata'     : jobFileRow['file_metadata'],
         'number_in_pattern' : jobFileRow['number_in_pattern']
       })
       
    numFiles += 1
        
  if jobDict:
    jobsList.append(jobDict)    

# NEED TO HANDLE SITUATION WHERE JOB CREATES A LOT OF OUTPUTS AND FALLS
# BELOW THE MIN AND MAX LIMITS IN ONE GO
  if numFiles < minFilesPerBulk:
    justin.logLine('Not enough jobs/files to process (%d)' % numFiles)
    return

  # Individual dictionaries with values needed for MetaCat add_child_dataset() 
  # and Rucio add_dataset() calls for each required dataset
  datasetsDict = {}

  metacatDatasetsDict = {} # for MetaCat declare_files() calls
  rucioRSEsDict       = {} # for Rucio add_replicas() call
  rucioDatasetsDict   = [] # for Rucio add_files_to_dataset

  # Go through the jobs/files to make the lists needed by the API calls
  for jobDict in jobsList:
    for fileDict in jobDict['files_list']:
      # Make numbered dataset name for this file
            
      nDataset = '%sn%04d' % (fileDict['destination'], 
                           int((fileDict['number_in_pattern']-1) 
                                 / justin.filesPerNumberedDestination))

      scopeNDataset = jobDict['scope_name'] + ':' + nDataset

      if scopeNDataset not in existingDatasets \
               and scopeNDataset not in datasetsDict:
        datasetsDict[scopeNDataset] = { 
               'workflow_id'      : jobDict['workflow_id'],
               'stage_id'         : jobDict['stage_id'],
               'pattern_id'       : jobDict['pattern_id'],
               'scope_name'       : jobDict['scope_name'],
               'lifetime_seconds' : fileDict['lifetime_seconds'],
               'parent_dataset'   : jobDict['destination'],               
               'child_dataset'    : nDataset }
      

      if scopeNDataset not in metacatDatasetsDict:
        metacatDatasetsDict[scopeNDataset] = []
              
      metacatDatasetsDict[scopeNDataset] = {
          'namespace' : jobDict['scope_name'],
          'name'      : fileDict['file_did'],
          'size'      : fileDict['size_bytes'], 
          'checksums' : { "adler32" : fileDict['adler32'] },
          'metadata'  : fileDict['file_metadata']
        }
 
      if fileDict['rse_name'] not in rucioRSEsDict:
        rucioRseDict[fileDict['rse_name']] = []
              
      rucioRSEsDict[fileDict['rse_name']] = {
          'scope'   : jobDict['scope_name'],
          'name'    : fileDict['file_did'],
          'bytes'   : fileDict['size_bytes'],
          'adler32' : fileDict['adler32']
        }

      if scopeNDataset not in rucioDatasetsDict:
        rucioDatasetsDict[scopeNDataset] = []
              
      rucioDatasetsDict[scopeNDataset] = {
          'scope' : jobDict['scope_name'],
          'name'  : fileDict['file_did']
        }

  for datasetDict in datasetsDict:
    try:
      clientMetaCat.create_dataset('%s:%s' % (datasetDict['scope_name'],
                                              datasetDict['child_dataset']) )

      clientMetaCat.add_child_dataset(
        datasetDict['scope_name'] + ':' + datasetDict['parent_dataset'],
        datasetDict['scope_name'] + ':' + datasetDict['child_dataset']   )

      didClientRucio.add_dataset(
        scope = datasetDict['scope_name'], 
        name  = datasetDict['child_dataset']
        )

      ruleClientRucio.add_add_replication_rule(
                     dids = [ {'scope' : datasetDict['scope_name'],
                               'name'  : datasetDict['child_dataset'] } ], 
                     copies = 1,
                     lifetime = datasetDict['lifetime_seconds'])
  
      justin.insertUpdate('INSERT INTO workflows_datasets '
                        'dataset_created=NOW(),'
                        'workflow_id=%d,stage_id=%d,pattern_id=%d,'
                        'dataset_name="%s",dataset_type="numbered"'
                        % (datasetDict['workflow_id'],
                           datasetDict['stage_id'],
                           datasetDict['pattern_id'],
                           datasetDict['child_dataset']))
    except Exception as e:
      logFile('Exciting: failed to create and record dataset %s:%s, error %s'
              % (datasetDict['scope_name'], datasetDict['child_dataset'],
                 str(e)))
      justin.conn.rollback()
      return
    else:
      # We commit dataset by dataset as they are in MetaCat and Rucio's
      # own databases by this point
      justin.conn.commit()

  for metacatDataset in metacatDatasetsDict:
    # Declare all the files for this dataset since declareFiles() requires
    # you do it per-dataset
    clientMetaCat.declareFiles(dataset = metacatDataset,
                               files = metacatDatasetsDict[metacatDataset])
# HANDLE ERRORS FOR THIS - HOW???

  for rucioRSE in rucioRSEsDict:
    # Declare all the replicas for this RSE since add_replicas() requires
    # you do it per-RSE. This call implicitly adds the DID to the catalog
    # of files too.
    repClientRucio.add_replicas(    
        rse   = rucioRSE,
        files = rucioRSEsDict[rucioRSE])
# HANDLE ERRORS FOR THIS - HOW???

  for rucioDataset in rucioDatasetsDict:
    # Declare all the files for this dataset since declareFiles() requires
    # you do it per-dataset
    didClientRucio.add_files_to_dataset(    
        scope = rucioDatasetsDict[rucioDataset]['scope'],
        name  = rucioDataset,
        files = rucioDatasetsDict[rucioDataset])        
# HANDLE ERRORS FOR THIS - HOW???

  for jobDict in jobsList:
    for fileDict in jobDict['files_list']:
      justin.insertUpdate('UPDATE files SET '
            'file_state=IF(stage > 0,"unallocated","finished") '
            'WHERE file_id=%d' % fileDict['file_id'])

    justin.insertUpdate('UPDATE files SET file_state="finished" '
                        'WHERE justin_job_id=%d' % jobDict['justin_job_id'])

    justin.insertUpdate('UPDATE jobs SET job_state="finished" '
                        'WHERE justin_job_id=%d' % jobDict['justin_job_id'])
# HANDLE ERRORS FOR THIS - HOW???

# ADD RETRIES
# ADD LOTS OF EVENT LOGGING

  justin.conn.commit()

def oneCycle():
  global clientMetaCat, didClientRucio, repClientRucio, ruleClientRucio
  
  try:
    clientMetaCat = \
      metacat.webapi.MetaCatClient(server_url = justin.metacatServerInputsURL, 
                               auth_server_url = justin.metacatAuthServerURL)
    clientMetaCat.login_x509('dunepro', justin.jobsProductionProxyFile)    

  except Exception as e:
    justin.logLine('Failed to contact MetaCat: ' + str(e))
    clientMetaCat = None

  try:
    didClientRucio  = rucio.client.didclient.DIDClient()
    repClientRucio  = rucio.client.replicaclient.ReplicaClient()
    ruleClientRucio = rucio.client.ruleclient.RuleClient()
  except Exception as e:
    justin.logLine('Failed to contact Rucio: ' + str(e))
    didClientRucio  = None
    repClientRucio  = None
    ruleClientRucio = None

  pingRucioMilliseconds = justin.pingRucioMilliseconds()

  justin.logLine('pingRucioMilliseconds returns %d' % pingRucioMilliseconds)
  if pingRucioMilliseconds < justin.overloadRucioMilliseconds:
    findFinishingJobs()
  else:
    justin.logLine('Skip findFinishingJobs()')
#
# PROGRAM MAIN
#

if __name__ == '__main__':
  justin.agentMainLoop('registration', oneCycle, sleepSeconds, 3600)
