#!/usr/bin/env python3
#
# justin-job-logs - justIN agent to save HTCondor job logs
#
# Copyright 2013-26, Andrew McNab for the University of Manchester
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

import os
import sys
import ssl
import stat
import json
import time
import base64
import shutil
import hashlib
import tempfile
import subprocess
import urllib.request
import pathlib
import xml.dom.minidom

## Needs MySQL-python RPM
#import MySQLdb

# WE NEED TO REMOVE OLD MySQLdb REFERENCES STILL!
import pymysql
pymysql.install_as_MySQLdb()
MySQLdb=pymysql

# Installed by pip3 install of Rucio
import rucio.client

import justin

sleepSeconds = 60

class justinError(Exception):
  pass


#
# Start of WebDAV uploads
#

def webdavCheckRemoteDirectories(sslContext, token, destinationDir):

  dirSplit = destinationDir.split('/')

  # Go down through the directories looking for the highest one that exists
  for highest in range(len(dirSplit) - 1, 1, -1): 
  
    # Don't do the check once we get down to the bare hostname 
    # But otherwise do stop if the directory exists already
    if highest > 2 and \
       webdavRemoteExists(sslContext, token, '/'.join(dirSplit[:highest + 1])):
      break
      
  for i in range(highest+1, len(dirSplit)):
    webdavRemoteDirCreate(sslContext, token, '/'.join(dirSplit[:i+1]))

def webdavRemoteExists(sslContext, token, url):

  httpRequest = urllib.request.Request(url,
                  headers = { 'User-Agent'     : 'justin-webdav-upload',
                              'Authorization'  : 'Bearer ' + token
                            },
                  method = 'HEAD')

  try:
    response = urllib.request.urlopen(httpRequest, context = sslContext)
    httpCode = response.status 
    reason   = response.msg

  except urllib.error.URLError as e:
    httpCode = e.code
    reason   = e.reason

  except Exception as e:
    print('Unknown error checking if %s exists: %s' % (url, str(e)), 
          file=sys.stderr)
    raise

  if httpCode == 404:
    print('%s does not exist' % url, file=sys.stderr)
    return False
    
  if httpCode == 200:
    print('%s exists' % url, file=sys.stderr)
    return True

  print('Unexpected HTTP code %d when checking for %s' % (httpCode, url),
        file=sys.stderr)
  print('Reason: ' + str(reason))
  raise RuntimeError('Unexpected HTTP code %d' % httpCode)
  
def webdavRemoteDirCreate(sslContext, token, url):

  httpRequest = urllib.request.Request(url,
                  headers = { 'User-Agent'     : 'justin-webdav-upload',
                              'Authorization'  : 'Bearer ' + token
                            },
                  method = 'MKCOL')

  try:
    response = urllib.request.urlopen(httpRequest, context = sslContext)    
    httpCode = response.status 

  except urllib.error.URLError as e:
    # For MKCOL, HTTP code 405 means directory already exists 
    # http://www.webdav.org/specs/rfc2518.html#rfc.section.8.3.2.p.4
    # Presumably another job created it ...
    if e.code == 405:
      print('%s already exists now!' % url, file=sys.stderr)
      return

    print('HTTP error: ' + str(e), file=sys.stderr)
    raise
    
  except Exception as e:
    print('Unknown error: ' + str(e), file=sys.stderr)
    raise
  
  if httpCode == 201:
    print('%s created, HTTP code %d' % (url, httpCode), file=sys.stderr)
    return

  print('Unexpected HTTP code %d when creating %s' % (httpCode, url),
        file=sys.stderr)
  raise RuntimeError('Unexpected HTTP code %d' % httpCode)
  
def webdavPutFile(token, source, destinationDir):

#  destDirSplit = destinationDir.split('/')
#
#  # Remove any final "/" and "//" after the one in "https://"
#  for i in range(2, len(destDirSplit)):
#    if destDirSplit[i] == '':
#      destDirSplit.pop(i)
#      
#  destinationDir = '/'.join(destDirSplit)

  sslContext = ssl.SSLContext()
  sslContext.verify_mode = ssl.CERT_REQUIRED
  sslContext.check_hostname = True
  sslContext.load_verify_locations(capath = 
                       '/cvmfs/grid.cern.ch/etc/grid-security/certificates')

  # Check the directory tree already exists and create if necessary
  webdavCheckRemoteDirectories(sslContext, token, destinationDir)

  sourceFile = source.split('/')[-1]
  destinationURL = destinationDir + '/' + sourceFile
    
  if webdavRemoteExists(sslContext, token, destinationURL):
    print('File already exists at %s' % destinationURL, file=sys.stderr)
    raise RuntimeError('File already exists')
  
  # Do a PUT to the desired destination, but expect a redirect
  httpRequest = urllib.request.Request(destinationURL,
                  headers = { 'User-Agent'     : 'justin-webdav-upload',
                              'Authorization'  : 'Bearer ' + token,
                              'Expect'         : '100-continue'
                            },
                  method = 'PUT')

  try:
    response = urllib.request.urlopen(httpRequest, context = sslContext)
    # Success is failure as we want a 307 redirect
    raise RuntimeError('No redirect received')

  except urllib.error.HTTPError as e:

    if e.code == 307:
      # And failure is success
      location = e.headers['Location']
    else:
      print('Unexpected HTTP code %d when creating %s' 
            % (e.code, destinationURL), file=sys.stderr)
      raise
    
  except Exception as e:
    print('Unexpected error when creating %s: %s' 
          % (str(e), destinationURL), file=sys.stderr)
    message = e.read().decode('utf-8')
    print(message, file=sys.stderr)
    raise

  print('Redirected to %s' % location, file=sys.stderr)

  #
  # Now use the URL we got from the redirection
  # 
  httpRequest = urllib.request.Request(location,
                  data = open(source, 'rb'),
                  headers = { 'User-Agent' : 'justin-webdav-upload' },
                  method = 'PUT')

  # Replace .has_header to prevent the default Content-Type 
  # IMO dCache should ignore Content-Type rather than reject the workflow
  httpRequest.has_header \
   = lambda header_name: (header_name == 'Content-type' or
                urllib.request.Request.has_header(httpRequest, header_name))

  try:
    response = urllib.request.urlopen(httpRequest, context = sslContext)
  except Exception as e:
    print('Error when creating %s: %s'
          % (destinationURL, str(e)), file=sys.stderr)
    raise

  if response.status == 201:
    # Created successfully
    print('Created ' + destinationURL)
    return

  print('Unexpected HTTP code %d when creating %s' 
        % (response.status, destinationURL), file=sys.stderr)
  raise RuntimeError('Unexpected HTTP code %d' % response.status)
#
# End of WebDAV uploads code
#


def fetchHTCondorJobLog(jobsubID):

  try:
    (clusterProc, schedd) = jobsubID.split('@')
    (cluster, proc)       = clusterProc.split('.')

    outcome = subprocess.run(['/var/lib/justin/justin-get-output',
                              str(cluster),
                              str(proc),
                              str(schedd),
                              justin.htcondorCollectors[0],
                              'remove'
                             ],
                              encoding = 'utf-8',
                              stderr   = subprocess.STDOUT,
                              stdout   = subprocess.PIPE,
                              timeout  = 120)
  except Exception as e:
    raise RuntimeError('For %s.%s@%s justin-get-output fails with %s' 
                       % (cluster, proc, schedd, str(e)))


  if outcome.returncode != 0:
    raise RuntimeError('For %s.%s@%s justin-get-output fails with '
                       'error code %d'
                       % (cluster, proc, schedd, outcome.returncode))

  return outcome.stdout

def saveTerminalJobsLogs():
  # Returns the number of jobs with logs saved this time

  justin.logLine('Start of saving HTCondor jobs')

  nowTime = int(time.time())

  terminalWithQuotes = ['"finishing"']
  for i in justin.jobStatesTerminal:
    terminalWithQuotes.append('"%s"' % i)
    
  # Get a list of jobs that are finishing or in terminal states without saved
  # wrapper logs that finishing in the last week and still have tries left 
  # (so we don't try forever)
  query = ('SELECT jobs.justin_job_id,jobsub_id,job_state,'
           'jobs.workflow_id,jobs.stage_id,jobs.site_id,jobs.entry_id,'
           'users.access_token,logs_url '
           'FROM jobs '
           'LEFT JOIN workflows ON jobs.workflow_id=workflows.workflow_id '
           'LEFT JOIN users ON users.user_id=workflows.user_id '
           'WHERE job_state IN (%s) '
           'AND logs_tries_left > 0 '
           'AND jobs.finishing_time > DATE_SUB(NOW(),INTERVAL 7 DAY) '
           'ORDER BY jobs.justin_job_id LIMIT 1000' 
           % ','.join(terminalWithQuotes))

  dbJobRows = justin.select(query)

  # Make a set of unique HTCondor schedd names from the database
  schedds = set()
  jobs    = {}
  for dbJobRow in dbJobRows:
    schedds.add( dbJobRow['jobsub_id'].split('@',1)[1] )
    
    logFile = dbJobRow['jobsub_id'].replace('@','.',1) + '.htcondor.log'
    # Save the job details - we just need this for the justIN events
    jobs[dbJobRow[logFile] = {
          'jobsub_id'     = dbJobRow['jobsub_id'],
          'justin_job_id' = dbJobRow['justin_job_id'],
          'workflow_id'   = dbJobRow['worklow_id'],
          'stage_id'      = dbJobRow['stage_id'],
          'site_id'       = dbJobRow['site_id'],
          'entry_id'      = dbJobRow['entry_id']
                                  }

  # Gather details of HTCondor jobs from our set of schedds
  condorJobs = {}  

  for scheddHostname in schedds:
    try: 
      outcome = subprocess.run(
               ['/usr/bin/condor_q',
                '-name',
                scheddHostname,
                '-pool',
                justin.htcondorCollectors[0],
                '-long:json',
                '-attributes',
                'clusterid,procid,jobstatus,enteredcurrentstatus'
               ],
               env      = dict(os.environ, 
                 BEARER_TOKEN_FILE='/etc/justin-secrets/bearer-token-file'),
               encoding = 'utf-8',
               stderr   = subprocess.STDOUT,
               stdout   = subprocess.PIPE,
               timeout  = 120
                            ) 
    except Exception as e:
      justin.logLine("condor_q fails with error: " + str(e))
      return 0

    justin.logLine('condor_q exit code: ' + str(outcome.returncode))
    
    if outcome.returncode != 0:
      justin.logLine("condor_q fails with return code %d" % outcome.returncode)
      return 0

    try:
      jsonJobs = json.loads(outcome.stdout)
    except:
      justin.logLine('Failed to load JSON output by condor_q')
      return 0

    for jsonJob in jsonJobs:  
      if 'jobstatus' not in jsonJob or \
         'enteredcurrentstatus' not in jsonJob or \
         'clusterid' not in jsonJob or \
         'procid' not in jsonJob:
        continue
      
      condorJobs['%d.%d@%s' % 
                 (jsonJob['clusterid'], 
                  jsonJob['procid'],
                  scheddHostname)] = \
           (jsonJob['jobstatus'], jsonJob['enteredcurrentstatus'])

  if not condorJobs:
    # If we get nothing at all then something must be going wrong
    justin.logLine('Failed to find any job info from HTCondor')
    return 0

  # Go back to the list of jobs from the database that have no wrapper log
  # saved and check each one against its HTCondor status, and try to fetch
  # logs
  
  subprocessDir  = tempfile.mkdtemp(prefix='justin-job-logs-')
  subprocessList = []

  for dbJobRow in dbJobRows:
    
    if dbJobRow['jobsub_id'] not in condorJobs:
      # if Condor is unaware of the job, then we're never going to get it
      justin.logLine('Job %s is not known to HTCondor - set logs_tries_left=0' 
              % dbJobRow['jobsub_id'])
      try:
        justin.insertUpdate('UPDATE jobs SET logs_tries_left=0 '
              'WHERE justin_job_id=%d' % dbJobRow['justin_job_id'])
      except Exception as e:
        # Log but otherwise ignore error
        justin.logLine('Failed to set logs_tries_left=0 for %s: %s'
                       % (dbJobRow['jobsub_id'], str(e)))
    
      continue      

    (jobStatus, enteredCurrentStatus) = condorJobs[dbJobRow['jobsub_id']]

    # If not yet in an HTCondor terminal state them skip for now
    if ((jobStatus != justin.htcondorREMOVED) and
        (jobStatus != justin.htcondorCOMPLETED)):
      justin.logLine('Job %s is in HTCondor state %d - skip for now' %
                (dbJobRow['jobsub_id'], jobStatus))
      continue

    # In a terminal state so try to get the logs and remove from spool
    # Decrement logs_tries_left to mark this attempt
    try:
      justin.insertUpdate('UPDATE jobs '
                          'SET logs_tries_left=logs_tries_left-1 '
                          'WHERE logs_tries_left > 0 AND '
                          'justin_job_id=%d' % dbJobRow['justin_job_id'])
    except Exception as e:
      justin.logLine('Failed to update logs_tries_left (%s) - ignoring'
                       % str(e))
      continue

    subprocessPID = os.fork()
    
    if subprocessPID == 0:
      # In subprocess, try to fetch logs and remove job
      try:
        wrapperLog = fetchHTCondorJobLog(dbJobRow['jobsub_id'])
      except Exception as e:
        justin.logLine('Failed fetching wrapper job log for %s: %s' %
                       (dbJobRow['jobsub_id'], str(e)))
      else:
        justin.logLine('Fetched wrapper job log for %s (%d)' %
                       (dbJobRow['jobsub_id'], dbJobRow['justin_job_id']))
        try:
          f = open(subprocessDir + '/' + 
                   dbJobRow['jobsub_id'].replace('@','.',1) + 
                   '.htcondor.log', 'w')
          f.write(wrapperLog)
          f.close()
        except Exception as e:
          justin.logLine('Failed writing wrapper log for %s: %s' %
                         (dbJobRow['jobsub_id'], str(e)))                         

        else:
          try:
            logLine('Uploading %s/%s.htcondor.log' 
                    % (dbJobRow['logs_url', dbJobRow['jobsub_id']))
            webdavPutFile(dbJobRow['access_token'],
                          subprocessDir + '/' + 
                          dbJobRow['jobsub_id'].replace('@','.',1) + 
                          '.htcondor.log',
                          dbJobRow['logs_url')

          except Exception as e:
            justin.logLine('Failed to save wrapper job log (%s) - skipping'
                           % str(e))
            try:
              # Record upload failures by removing the log file, as if we
              # failed to fetch it from HTCondor
              os.remove(subprocessDir + '/' + 
                        dbJobRow['jobsub_id'].replace('@','.',1) + 
                        '.htcondor.log')
            except:
              pass
            

      sys.exit(0)
          
    # In parent
    justin.logLine('Forked %d for %s (%d)' % 
                   (subprocessPID, 
                    dbJobRow['jobsub_id'], 
                    dbJobRow['justin_job_id']))
    subprocessList.append(subprocessPID)

    if len(subprocessList) > justin.parallelJobLogs:
      # We only fork so many times
      break

  # Wait until all subprocesses have finished
  for count in range(0, 31):
    anyActive = False
    for i in subprocessList:
      if justin.pidIsActive(i):
        anyActive = True
        break
    
    if not anyActive:
      break
      
    time.sleep(1)

  # Kill any still running
  if anyActive:
    for i in subprocessList:
      if justin.pidIsActive(i):
        try:
          os.kill(cyclePid)
        except Exception:
          # Not much we can do except log it
          justin.logLine('Kill of %d fails with: %s' % (i, str(e)))

  # Go through the subprocess outputs and save logs in the database
  numberSaved = 0
  for logFile in os.listdir(subprocessDir):
    jobsubID = jobs[logFile]['jobsub_id']
    justin.logLine('Processing %s' % jobsubID)
      
    try:
      # If we got the jobsubID from a file then we assume the 
      # WebDAV upload worked and we're done with this job
      justin.insertUpdate('UPDATE jobs '
              'SET logs_tries_left=0 '
              'WHERE justin_job_id=%d' % jobs[logFile]['justin_job_id'])
    except Exception as e:
      justin.logLine('Failed to update job %s (%s) - skipping'
                     % (jobsubID, str(e)))
      continue

    else:
      justin.logEvent(eventTypeID = justin.event_JOB_HTCONDOR_LOGS_CACHED,
                      justinJobID = jobs[logFile]['justin_job_id'],
                      workflowID  = jobs[logFile]['worklow_id'],
                      stageID     = jobs[logFile]['stage_id'],
                      siteID      = jobs[logFile]['site_id'],
                      entryID     = jobs[logFile]['entry_id'])

    # Whatever else happened, we log that the HTCondor job was removed
    numberSaved += 1
    justin.logEvent(eventTypeID = justin.event_JOB_REMOVED_FROM_HTCONDOR,
                      justinJobID = jobs[logFile]['justin_job_id'],
                      workflowID  = jobs[logFile]['worklow_id'],
                      stageID     = jobs[logFile]['stage_id'],
                      siteID      = jobs[logFile]['site_id'],
                      entryID     = jobs[logFile]['entry_id'])

  # All ok, so remove temp directory and commit everything to the DB
  shutil.rmtree(subprocessDir, ignore_errors = True)
  justin.conn.commit()

  return numberSaved
 
def oneCycle():

  if saveTerminalJobsLogs() == 0:
    # Only sleep between cycles if we found no logs to save
    # This means if the job rate is big enough, we never sleep
    justin.logLine('No logs saved, so sleep for %d seconds' % sleepSeconds)
    time.sleep(sleepSeconds)
#
# PROGRAM MAIN
#

if __name__ == '__main__':
  # 0 means no sleeps between cycles. We do the sleeps in oneCycle() itself
  justin.agentMainLoop('job-logs', oneCycle, 0, 3600)
