#!/usr/bin/env python3
#
# justin-registration - justIN Registration Agent
#
# Copyright 2013-26, Andrew McNab for the University of Manchester
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

import os
import sys
import ssl
import stat
import json
import time
import base64
import hashlib
import tempfile
import subprocess
import urllib.request
import pathlib
import xml.dom.minidom

## Needs MySQL-python RPM
#import MySQLdb

# WE NEED TO REMOVE OLD MySQLdb REFERENCES STILL!
import pymysql
pymysql.install_as_MySQLdb()
MySQLdb=pymysql

# Installed by pip3 install of Rucio
import rucio.client
import metacat.webapi

import justin

sleepSeconds         = 60
maxFilesPerBulk      = 500
minFilesPerBulk      = 1

clientMetaCat        = None
didClientRucio       = None
repClientRucio       = None

class justinError(Exception):
  pass

def getWorkflowsDatasets():
  # Return a list of all created datasets for all running wofklows
  
  try:
    query = ('SELECT dataset_name,scopes.scope_name '
             'FROM workflows_datasets '
             'LEFT JOIN workflows '
             'ON workflows.workflow_id=workflows_datasets.workflow_id '
             'LEFT JOIN scopes '
             'ON workflows.scope_id=scopes.scope_id '
             'WHERE workflow_state="running"')
             
    rows = justin.select(query)
             
  except Exception as e:
    justin.logLine('Failed to get list of datasets: ' + str(e))
    return {}
    
  datasetsList = []
  for row in rows:
    runningDatasets.append(row['scope_name'] + ':' + row['dataset_name'])
    
  return datasetsList    
  
def findFinishingJobs():
  # Find jobs in the finishing state, register their output files, and mark
  # jobs as finished
  
  justin.logLine('Start of finding finishing jobs')

  existingDatasets = getRunningWorkflows()
  if not existingDatasets:
    return

  # Find finishing jobs and their output files
  # We limit this to maxFilesPerBulk + 1 to get the start of the next
  # job's files to detect the end of the last job we actually want
  try:
    query = ('SELECT justin_job_id,file_id,replica_id,pfn,destination,'
             'file_metadata,number_in_pattern,scope_name '
             'FROM jobs '
             'LEFT JOIN workflows ON workflows.workflow_id=jobs.workflow_id '
             'LEFT JOIN scopes ON scopes.scope_id=workflows.scope_id '
             'LEFT JOIN files '
             'ON files.creator_justin_job_id=jobs.justin_job_id '
             'AND files.file_state="registering" '
             'LEFT JOIN replicas '
             'ON files.file_id=replicas.file_id '
             'LEFT JOIN stages_outputs '
             'ON files.workflow_id=stages_outputs.workflow_id '
             'AND files.creator_stage_id=stages_outputs.stage_id '
             'AND files.creator_pattern_id=stages_outputs.pattern_id '
             'WHERE jobs_state="finishing" AND files.file_id<>NULL '
             'AND replicas.replica_id<>NULL '
             'ORDER BY justin_job_id,file_id '
             'LIMIT %d' % (maxFilesPerBulk + 1))

    jobsFilesRows = justin.select(query)
  except:
    justin.logLine('Failed to get list of finishing jobs/files')
    return

  # Get output files from jobs, grouped by job so each job's files' 
  # registrations are all or none so we can fail whole jobs to force retries

  jobsList           = []
  jobDict            = {}
  numFiles           = 0
  currentJustinJobId = 0
  
  for jobFileRow in jobsFilesRows:
  
    if jobFileRow['justin_job_id'] != currentJustinJobId:
      # Save previous job dict
      if jobDict:
        jobsList.append(jobDict)

      # Create new job dict
      jobDict = { 'justin_job_id' : jobFileRow['justin_job_id'], 
                  'scope_name'    : jobFileRow['scope_name'],
                  'files_list' : [] }

    jobDict['files_list'].append(
       { 'file_id'           : jobFileRow['file_id'],
         'replica_id'        : jobFileRow['replica_id'],
         'pfn'               : jobFileRow['pfn'],
         'destination'       : jobFileRow['destination'],
         'file_metadata'     : jobFileRow['file_metadata'],
         'number_in_pattern' : jobFileRow['number_in_pattern']
       })
       
    numFiles += 1
        
  if jobDict:
    jobsList.append(jobDict)    

# NEED TO HANDLE SITUATION WHERE JOB CREATES A LOT OF OUTPUTS AND FALLS
# BELOW THE MIN AND MAX LIMITS IN ONE GO
  if numFiles < minFilesPerBulk:
    justin.logLine('Not enough jobs/files to process (%d)' % numFiles)
    return

  # Individual dictionaries with values needed for MetaCat add_child_dataset() 
  # and Rucio add_dataset() calls for each required dataset
  datasetsDict = {}

  metacatFilesList = []       # for MetaCat declare_files() call
  rucioFilesList   = []       # for Rucio add_dids() call
  rucioFilesDatasetsList = [] # for Rucio add_files_to_datasets

  # Go through the jobs/files to make the lists needed by the API calls
  for jobDict in jobsList:
    for fileDict in jobDict['files_list']:
      # Make numbered dataset name for this file
            
      nDataset = '%sn%04d' % (fileDict['destination'], 
                           int((fileDict['number_in_pattern']-1) 
                                 / justin.filesPerNumberedDestination))

      scopeNDataset = jobDict['scope_name'] + ':' + nDataset

      if scopeNDataset not in existingDatasets \
               and scopeNDataset not in datasetsDict:
        datasetsDict[scopeNDataset] = { 
               'scope_name'     : jobDict['scope_name'],
               'parent_dataset' : jobDict['destination'],
               'child_dataset'  : nDataset }
      
      metacatFilesList.append({
                 })
 
      rucioFilesList.append({
                 })

      rucioFilesDatasetsList.append({
                 })


  for datasetDict in datasetsDict:
    # CALL A FUNCTION TO CREATE THE NUMBERED DATASETS FOR THESE FILES 
    clientMetaCat.add_child_dataset(
      datasetDict['scope_name'] + ':' + datasetDict['parent_dataset'],
      datasetDict['scope_name'] + ':' + datasetDict['child_dataset']   )


    didClientRucio.add_dataset(
      scope = datasetDict['scope_name'], 
      name  = datasetDict['child_dataset'],
      rules = [{'copies': 1 }]
      )
  
  # DO THE METACAT BULK REGISTRATION OF FILES IN DATASETS
  # DO THE RUCIO BULK REGISTRATION OF FILES AND FILES TO DATASETS AND
  # REPLICAS


  # MARK ALL THE FILES AS FINISHED OR UNALLOCATED, AND JOBS AS FINISHED
  # THE FINDER WILL MARK THE WORKLOWS AS FINISHED WHEN READY


  justin.conn.commit()

def oneCycle():
  global clientMetaCat, didClientRucio, repClientRucio
  
  try:
    clientMetaCat = \
      metacat.webapi.MetaCatClient(server_url = justin.metacatServerInputsURL, 
                               auth_server_url = justin.metacatAuthServerURL)
    clientMetaCat.login_x509('dunepro', justin.jobsProductionProxyFile)    

  except Exception as e:
    justin.logLine('Failed to contact MetaCat: ' + str(e))
    clientMetaCat = None

  try:
    didClientRucio = rucio.client.didclient.DIDClient()
    repClientRucio = rucio.client.replicaclient.ReplicaClient()
  except Exception as e:
    justin.logLine('Failed to contact Rucio: ' + str(e))
    didClientRucio = None
    repClientRucio = None

  pingRucioMilliseconds = justin.pingRucioMilliseconds()

  justin.logLine('pingRucioMilliseconds returns %d' % pingRucioMilliseconds)
  if pingRucioMilliseconds < justin.overloadRucioMilliseconds:
    findFinishingJobs()
  else:
    justin.logLine('Skip findFinishingJobs()')
#
# PROGRAM MAIN
#

if __name__ == '__main__':
  justin.agentMainLoop('registration', oneCycle, sleepSeconds, 3600)
