#!/bin/bash
#
# justin-create-x509-proxies - create X.509 proxies for justIN 
#
# Copyright 2013-25, Andrew McNab for the University of Manchester
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

(

HTTPD_USER_GROUP=dunejustin.dunejustin

echo
echo '======= Create justin-jobs-production.proxy.pem'
echo
date
rm -f /tmp/justin-jobs-production.proxy.pem.tmp
voms-proxy-init \
 -cert /etc/justin-secrets/justin-jobs-production.dune.hep.ac.uk.cert.pem \
 -key  /etc/justin-secrets/justin-jobs-production.dune.hep.ac.uk.key.pem \
 -voms dune:/dune/Role=Production \
 -valid 168:0 \
 -out /tmp/justin-jobs-production.proxy.pem.tmp 
 
if [ $? = 0 -a -s /tmp/justin-jobs-production.proxy.pem.tmp ]
then
  cp -f /tmp/justin-jobs-production.proxy.pem.tmp \
        /tmp/x509up_u`id -u dunejustin`
  chown dunejustin.dunejustin /tmp/x509up_u`id -u dunejustin`

  chown $HTTPD_USER_GROUP /tmp/justin-jobs-production.proxy.pem.tmp
  mv -f /tmp/justin-jobs-production.proxy.pem.tmp \
        /tmp/justin-jobs-production.proxy.pem

  voms-proxy-info -all -file /tmp/justin-jobs-production.proxy.pem
fi

echo
echo '======= Create justin-jobs-no-roles.proxy.pem'
echo
rm -f /tmp/justin-jobs-no-roles.proxy.pem.tmp
voms-proxy-init \
 -cert /etc/justin-secrets/justin-jobs-no-roles.dune.hep.ac.uk.cert.pem \
 -key  /etc/justin-secrets/justin-jobs-no-roles.dune.hep.ac.uk.key.pem \
 -voms dune \
 -valid 168:0 \
 -out /tmp/justin-jobs-no-roles.proxy.pem.tmp 

if [ $? = 0 -a -s /tmp/justin-jobs-no-roles.proxy.pem.tmp ]
then
  chown $HTTPD_USER_GROUP /tmp/justin-jobs-no-roles.proxy.pem.tmp
  mv -f /tmp/justin-jobs-no-roles.proxy.pem.tmp \
        /tmp/justin-jobs-no-roles.proxy.pem

  voms-proxy-info -all -file /tmp/justin-jobs-no-roles.proxy.pem
fi
echo
date
echo

) >>/var/log/justin/create-x509-proxies-${CONTAINER_NAME:-xxx} 2>&1
