#!/bin/sh
#
# justin-create-x509-proxies - create X.509 proxies for justIN 
#
# Copyright 2013-24, Andrew McNab for the University of Manchester
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

(

HTTPD_USER_GROUP=dunejustin.dunejustin

echo
echo '======= Create justin-jobs-production.proxy.pem'
echo
voms-proxy-init \
 -cert /etc/grid-security/justin-jobs-production.cert.pem \
 -key  /etc/grid-security/justin-jobs-production.key.pem \
 -voms dune:/dune/Role=Production \
 -valid 168:0 \
 -out /etc/grid-security/justin-jobs-production.proxy.pem.tmp 
 
if [ $? = 0 -a -s /etc/grid-security/justin-jobs-production.proxy.pem.tmp ]
then
  cp -f /etc/grid-security/justin-jobs-production.proxy.pem.tmp \
        /etc/grid-security/x509up_u1026
  chown dunejustin.dunejustin /etc/grid-security/x509up_u1026

  chown $HTTPD_USER_GROUP /etc/grid-security/justin-jobs-production.proxy.pem.tmp
  mv -f /etc/grid-security/justin-jobs-production.proxy.pem.tmp \
        /etc/grid-security/justin-jobs-production.proxy.pem

  voms-proxy-info -all -file /etc/grid-security/justin-jobs-production.proxy.pem
fi

echo
echo '======= Create justin-jobs-no-roles.proxy.pem'
echo
voms-proxy-init \
 -cert /etc/grid-security/justin-jobs-no-roles.cert.pem \
 -key  /etc/grid-security/justin-jobs-no-roles.key.pem \
 -voms dune \
 -valid 168:0 \
 -out /etc/grid-security/justin-jobs-no-roles.proxy.pem.tmp 

if [ $? = 0 -a -s /etc/grid-security/justin-jobs-no-roles.proxy.pem.tmp ]
then
  chown $HTTPD_USER_GROUP /etc/grid-security/justin-jobs-no-roles.proxy.pem.tmp
  mv -f /etc/grid-security/justin-jobs-no-roles.proxy.pem.tmp \
        /etc/grid-security/justin-jobs-no-roles.proxy.pem

  voms-proxy-info -all -file /etc/grid-security/justin-jobs-no-roles.proxy.pem
fi

echo
echo '======= Create justin-jobs-analysis.proxy.pem'
echo
voms-proxy-init \
 -cert /etc/grid-security/justin-jobs-analysis.cert.pem \
 -key  /etc/grid-security/justin-jobs-analysis.key.pem \
 -voms dune \
 -valid 168:0 \
 -out /etc/grid-security/justin-jobs-analysis.proxy.pem.tmp 

if [ $? = 0 -a -s /etc/grid-security/justin-jobs-analysis.proxy.pem.tmp ]
then
  chown $HTTPD_USER_GROUP /etc/grid-security/justin-jobs-analysis.proxy.pem.tmp
  mv -f /etc/grid-security/justin-jobs-analysis.proxy.pem.tmp \
        /etc/grid-security/justin-jobs-analysis.proxy.pem

  voms-proxy-info -all -file /etc/grid-security/justin-jobs-analysis.proxy.pem
fi

) >/var/log/justin/create-x509-proxies.log 2>&1
