#!/bin/sh
#
# Convert the justin.1 man page to a Markdown formatted file
#

if [ ! -r ../commands/justin.1 ] ; then
 echo 'Run this command in ../docs so man page is at ../commands/justin.1 !'
 exit 1
fi

(

cat <<EOF
# justin command man page
This man page is distributed along with the 
[justin command](justin_command.md) itself.

EOF
groff -mandoc -Tascii -P -b ../commands/justin.1 | sed 's/.*/    &/'

) > justin_command.man_page.md

(

cat <<EOF
# justin-test-jobscript command man page
This man page is distributed along with the 
justin-test-jobscripts command itself.

EOF
groff -mandoc -Tascii -P -b ../commands/justin-test-jobscript.1 | sed 's/.*/    &/'

) > jobscripts.interactive_tests.man_page.md

(

cat <<EOF
# justin-cvmfs-upload command man page
This man page is distributed along with the 
justin-cvmfs-upload command itself.

EOF
groff -mandoc -Tascii -P -b ../commands/justin-cvmfs-upload.1 | sed 's/.*/    &/'

) > jobscripts.rcds.man_page.md

(

cat <<EOF
# justin-webdav-upload command man page
This man page is distributed along with the 
justin-webdav-upload command itself.

EOF
groff -mandoc -Tascii -P -b ../commands/justin-webdav-upload.1 | sed 's/.*/    &/'

) > jobscripts.webdav-upload.man_page.md

