#!/bin/sh
#
# Convert the justin.1 man page to a Markdown formatted file
#

if [ ! -r ../commands/justin.1 ] ; then
 echo 'Run this command in ../docs so man page is at ../commands/justin.1 !'
 exit 1
fi

(

cat <<EOF
# justin command man page
This man page is distributed along with the 
[justin command](justin_command.md) itself.

EOF
mandoc -T ascii ../commands/justin.1 | col -b | sed 's/.*/    &/'

) > justin_command.man_page.md

(

cat <<EOF
# justin-fetch-logs command man page
This man page is distributed along with the 
justin-fetchlogs command itself.

EOF
mandoc -T ascii ../commands/justin-fetch-logs.1 | col -b | sed 's/.*/    &/'

) > justin-fetch-logs.man_page.md

(

cat <<EOF
# justin-test-jobscript command man page
This man page is distributed along with the 
justin-test-jobscripts command itself.

EOF
mandoc -T ascii ../commands/justin-test-jobscript.1 | col -b | sed 's/.*/    &/'

) > jobscripts.interactive_tests.man_page.md

(

cat <<EOF
# justin-cvmfs-upload command man page
This man page is distributed along with the 
justin-cvmfs-upload command itself.

EOF
mandoc -T ascii ../commands/justin-cvmfs-upload.1 | col -b | sed 's/.*/    &/'

) > jobscripts.rcds.man_page.md

(

cat <<EOF
# justin-webdav-upload command man page
This man page is distributed along with the 
justin-webdav-upload command itself.

EOF
mandoc -T ascii ../commands/justin-webdav-upload.1 | col -b | sed 's/.*/    &/'

) > jobscripts.webdav-upload.man_page.md

