#!/bin/sh
#
# Convert the workflow.1 man page to a Markdown formatted file
#

if [ ! -r ../commands/workflow.1 ] ; then
 echo 'Run this command in ../docs so man page is at ../commands/workflow.1 !'
 exit 1
fi

(

cat <<EOF
## Workflow command man page
This man page is distributed along with the 
[workflow command](workflow-command.md) itself.
EOF
echo '```'
groff -mandoc -Tascii -P -b ../commands/workflow.1 
echo '```'

) > workflow-man-page.md
